package com.savbill.commonGateway.moules.PaymentConfig.model;

public class PaymentGatewayConfigurationConstant {

    public interface PAYMENT_GATEWAY_LIST{
        String PAYTM = "PAYTM";

        String FLUTTERWAVE = "FLUTTERWAVE";

        String ERRICSON = "ERRICSON";

        String PHONEPE ="PHONEPE";

        String AIRTEL = "AIRTEL";
    }

    public interface PAYTM{

        String PAYMENT_GATEWAY_NAME = "PAYMENT_GATEWAY_NAME";
        String REDIRECT_CWSC_URL = "REDIRECT_CWSC_URL";
        String REDIRECT_CAPTIVE_URL = "REDIRECT_CAPTIVE_URL";
        String PAYTM_CALLBACK_URL = "PAYTM_CALLBACK_URL";
        String PAYTM_CMS_ADDRESS = "PAYTM_CMS_ADDRESS";
        String PAYTM_CHANNEL_ID = "PAYTM_CHANNEL_ID";
        String PAYTM_INDUSTRY_TYPE_ID = "PAYTM_INDUSTRY_TYPE_ID";
        String PAYTM_MERCHENT_ID = "PAYTM_MERCHENT_ID";
        String PAYTM_WEBSITE = "PAYTM_WEBSITE";
        String PAYTM_MERCHANT_KEY = "PAYTM_MERCHANT_KEY";
        String PAYTM_PAYMENT_URL = "PAYTM_PAYMENT_URL";
        String PAYTM_PAYMENT_LINK_URL = "PAYTM_PAYMENT_LINK_URL";

        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";

    }

    public interface FLUTTER_WAVE{

        String PAYMENT_GATEWAY_NAME = "PAYMENT_GATEWAY_NAME";
        String CWSC_REDIRECT_URL= "CWSC_REDIRECT_URL";
        String CAPTIVE_REDIRECT_URL = "CAPTIVE_REDIRECT_URL";
        String FLUTTERWAVE_PUBLIC_KEY = "FLUTTERWAVE_PUBLIC_KEY";

        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";

        String FLUTTERWAVE_PAYMENT_CALLBACK_URL = "FLUTTERWAVE_PAYMENT_CALLBACK_URL";

        String FLUTTERWAVE_RENEW_CWSC_CALLBACK_URL = "FLUTTERWAVE_RENEW_CWSC_CALLBACK_URL";

        String FLUTTERWAVE_CHANGE_PLAN_CWSC_CALLBACK_URL = "FLUTTERWAVE_CHANGE_PLAN_CWSC_CALLBACK_URL";

        String FLUTTERWAVE_CAPTIVE_BUY_PLAN = "FLUTTERWAVE_CAPTIVE_BUY_PLAN";


    }

    public interface MTN_ERRICSON{
        String PAYMENT_GATEWAY_NAME = "PAYMENT_GATEWAY_NAME";
    }


    public interface PHONEPE{

        String PHONEPE_MERCHANT_ID = "PHONEPE_MERCHANT_ID";

        String PHONEPE_MERCHANT_USERID = "PHONEPE_MERCHANT_USERID";

        String PHONEPE_CALLBACK_URL = "PHONEPE_CALLBACK_URL";

        String PHONEPE_SALT_INDEX = "PHONEPE_SALT_INDEX";

        String PHONEPE_SALT_KEY = "PHONEPE_SALT_KEY";
        String PHONEPE_REDIRECT_URL = "PHONEPE_REDIRECT_URL";

        String PHONPE_REDIRECT_MODE = "PHONPE_REDIRECT_MODE";

        String PHONPE_PAYMENT_INSTRUMENT_TYPE = "PHONPE_PAYMENT_INSTRUMENT_TYPE";

        String PHONPE_GATEWAY_URL = "PHONPE_GATEWAY_URL";

    }

    public interface AIRTEL{
        String AIRTEL_CLIENT_ID = "AIRTEL_CLIENT_ID";

        String AIRTEL_CLIENT_SECRET = "AIRTEL_CLIENT_SECRET";

        String AIRTEL_GRANT_TYPE = "AIRTEL_GRANT_TYPE";
        String AIRTEL_REFERENCE = "AIRTEL_REFERENCE";

        String AIRTEL_API_URL = "AIRTEL_API_URL";

        String COUNTRY = "COUNTRY";
        String CURRENCY = "CURRENCY";

        String AIRTEL_CWSC_CALLBACK_URL = "AIRTEL_CWSC_CALLBACK_URL";

        String AIRTEL_CWSC_CAPTIVE_URL = "AIRTEL_CWSC_CAPTIVE_URL";

        String STAFFUSER_USERNAME = "STAFFUSER_USERNAME";
        String STAFFUSER_PASSWORD = "STAFFUSER_PASSWORD";
        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";
        String SCHEDULED_CALL_TIME = "SCHEDULED_CALL_TIME";

    }
}
