<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://api.act.com/"
           xmlns:api="http://api.act.com/"
           elementFormDefault="qualified">

    <!-- Request Element -->
    <xs:element name="wsSessionLoginStatus">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="ipAddress" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Response Element -->
    <xs:element name="wsSessionLoginStatusResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="SessionLoginStatus">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="requestId" type="xs:string" minOccurs="0"/>
                            <xs:element name="responeCode" type="xs:int" minOccurs="0"/>
                            <xs:element name="responseMessage" type="xs:string" minOccurs="0"/>
                            <xs:element name="result" type="xs:boolean" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
