<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:api="http://api.act.com/"
           targetNamespace="http://api.act.com/"
           elementFormDefault="qualified">

    <!-- Define the wsGetAccountDetails request -->
    <xs:element name="wsGetAccountDetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="userName" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Define the wsGetAccountDetailsResponse -->
    <xs:element name="wsGetAccountDetailsResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="GetAccountDetails">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="item" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="key" type="xs:string"/>
                                        <xs:element name="value" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="password" type="xs:string"/>
                            <xs:element name="requestId" type="xs:string"/>
                            <xs:element name="responeCode" type="xs:int"/>
                            <xs:element name="responseMessage" type="xs:string"/>
                            <xs:element name="serviceId" type="xs:string"/>
                            <xs:element name="userName" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="GetAccountDetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="userName" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Define the wsGetAccountDetailsResponse -->
    <xs:element name="GetAccountDetailsResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="GetAccountDetails">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="item" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="key" type="xs:string"/>
                                        <xs:element name="value" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="password" type="xs:string"/>
                            <xs:element name="requestId" type="xs:string"/>
                            <xs:element name="responeCode" type="xs:int"/>
                            <xs:element name="responseMessage" type="xs:string"/>
                            <xs:element name="serviceId" type="xs:string"/>
                            <xs:element name="userName" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
