<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://api.act.com/"
           xmlns:tns="http://api.act.com/">

    <xs:complexType name="subscriberMapEntry">
        <xs:sequence>
            <xs:element name="key" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="getAccountDetailsResponse">
        <xs:sequence>
            <xs:element name="item" type="tns:subscriberMapEntry" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="password" type="xs:string" minOccurs="0"/>
            <xs:element name="requestId" type="xs:string" minOccurs="0"/>
            <xs:element name="responeCode" type="xs:int"/>
            <xs:element name="responseMessage" type="xs:string" minOccurs="0"/>
            <xs:element name="serviceId" type="xs:string" minOccurs="0"/>
            <xs:element name="userName" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Define response element -->
    <xs:element name="wsGetAccountDetailsResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="GetAccountDetails" type="tns:getAccountDetailsResponse"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>