export const FLUTTERWAVE_CONSTANT = {
  FLUTTERWAVE_RENEW_CWSC_CALLBACK_URL: "FLUTTERWAVE_RENEW_CWSC_CALLBACK_URL",
  FLUTTERWAVE_PUBLIC_KEY: "FLUTTERWAVE_PUBLIC_KEY",
  FLUTTERWAVE_CURRENCY: "FLUTTERWAVE_CURRENCY",
};

export const RAZORPAY_CONSTANT = {
  RAZORPAY_KEY_ID: "RAZORPAY_KEY_ID",
  RAZORPAY_SECRET_KEY: "RAZORPAY_SECRET_KEY",
  RAZORPAY_CURRENCY: "RAZORPAY_CURRENCY",
  RAZORPAY_CALLBACK_URL: "RAZORPAY_CALLBACK_URL",
};
