server.port=41080
app.name=SavbillIntegrationSystem
spring.datasource.url=jdbc:mysql://localhost:3306/savbillintegrationsystem?allowPublicKeyRetrieval=true&useSSL=false&autoreconnect=true&createDatabaseIfNotExist=true

spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
#spring.mvc.view.suffix=.html
spring.http.multipart.max-file-size=10MB
spring.http.multipart.max-request-size=10MB
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.com.savbill=DEBUG
logging.level.org.springframework=INFO
logging.level.root=INFO
#logging.level.org.hibernate.type=TRACE
logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.jdbc.core=INFO
server.error.whitelabel.enabled=false
#spring.jpa.properties.org.hibernate.envers.default_schema=audit
spring.jpa.properties.hibernate.integration.envers.enabled=false
javers.sqlSchemaManagementEnabled=false
javers.auditableAspectEnabled=false
javers.springDataAuditableRepositoryAspectEnabled=false
logging.level.org.springframework.transaction=Info
logging.level.org.springframework.transaction.interceptor=TRACE

cronjobtimeforsendbill=0 0 0 */3 * *
cronjobtimeforsendcreditnote=0 0 0 */3 * *
cronjobtimeforairtelpaymentstatus=0 1 */3 * * *
environmentInfo = "staging"
serverIpForAudit = ""
momo.scheduled.time = 7
max.poll.records=15000
fetch.max.bytes=524288000
fetch.min.bytes=1

#spring.thymeleaf.enabled=true
#
#logging.level.org.thymeleaf=DEBUG
#logging.level.org.springframework.web.servlet=DEBUG
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html

logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web.servlet=DEBUG

#kafka.bootstrapAddress=127.0.0.1
#kafka.port=9092
kafka-url=127.0.0.1:9092
kafka.max.request.size=2000000000
# Enable resource mappings
spring.web.resources.add-mappings=true

# Specify the locations of static resources
spring.web.resources.static-locations=classpath:/xsd/
logging.level.org.springframework.ws.server.MessageTracing=DEBUG
logging.level.org.springframework.ws.client.MessageTracing=DEBUG
logging.level.org.springframework.ws=DEBUG



staff.username=admin
staff.password=admin@123

feign.client.config.default.connectTimeout=50000
feign.client.config.default.readTimeout=50000

isprolename=ISP_Admin
superadmin.username=superadmin
superadmin.password=superadmin@2021@SUPERADMIN
superadmin.mvnoname=OAM

admin.username=admin
admin.password=admin@123
admin.mvnoname=admin

management.endpoints.web.exposure.include=prometheus,metrics
servicearea.name = 1
defaultplan = 300 MBPS 30 Days

#This property added for image resolution

qr.width = 300
qr.height = 300

tradelance.callback-url=https://merchant.252.co.ug/SavannaFibre/ipn.php


mobile.prefix=3
selcom.reverseFlow.mvnoId=3

