#Default port for eureka server
server:
  port: ${PORT:8761}

spring:
  application:
    name: savbill-server
    
eureka:
  datacenter: Main
  environment: Production
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/