<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ns="http://api.act.com/"
           targetNamespace="http://api.act.com/"
           elementFormDefault="qualified">


    <!-- Definition of the wsGetAccountName element in the api namespace -->
    <xs:element name="wsGetAccountName">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="ipAddress" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Definition of GetAccountName element in the response -->
    <xs:element name="wsGetAccountNameResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="accountName" type="xs:string" minOccurs="1"/>
                <xs:element name="requestId" type="xs:string" minOccurs="1"/>
                <xs:element name="responeCode" type="xs:int" minOccurs="1"/>
                <xs:element name="responseMessage" type="xs:string" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="GetAccountName">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="ipAddress" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Definition of GetAccountName element in the response -->
    <xs:element name="GetAccountNameResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="accountName" type="xs:string" minOccurs="1"/>
                <xs:element name="requestId" type="xs:string" minOccurs="1"/>
                <xs:element name="responeCode" type="xs:int" minOccurs="1"/>
                <xs:element name="responseMessage" type="xs:string" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>