<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://npm.redback.com"
           xmlns="http://npm.redback.com"
           elementFormDefault="qualified">

    <!-- Request Element -->
<!--    <xs:element name="getBalanceRequest">-->
<!--        <xs:complexType>-->
<!--            <xs:sequence>-->
<!--                <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified"/>-->
<!--            </xs:sequence>-->
<!--        </xs:complexType>-->
<!--    </xs:element>-->

    <!-- Response Element -->
    <xs:element name="getBalanceResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="result" type="xs:anyURI"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- MultiRef ResultType -->
    <xs:complexType name="ResultType">
        <xs:sequence>
            <xs:element name="href" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Fault Message for InvalidSubscriberAccountException -->
    <xs:complexType name="InvalidSubscriberAccountException">
        <xs:sequence>
            <xs:element name="message" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
