<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://subscription.ws.nvsmx.elitecore.com/"
           xmlns:tns="http://subscription.ws.nvsmx.elitecore.com/">


    <xs:element name="wsGetBalanceResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="return" type="tns:getBalanceEnquiryResponse"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="getBalanceEnquiryResponse">
        <xs:complexContent>
            <xs:extension base="tns:balanceEnquiryResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="subscriptionInfo" nillable="true" type="tns:subscriptionInfoData"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="subscriptionInfoData">
        <xs:complexContent>
            <xs:extension base="tns:subscriptionInformationData">
                <xs:sequence>
                    <xs:element minOccurs="0" name="carryForword" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="subscriptionInformationData">
        <xs:sequence>
            <xs:element minOccurs="0" name="addOnStatus" type="tns:subscriptionState"/>
            <xs:element minOccurs="0" name="addonSubscriptionId" type="xs:string"/>
            <xs:element minOccurs="0" name="endTime" type="xs:long"/>
            <xs:element minOccurs="0" name="packageDescription" type="xs:string"/>
            <xs:element minOccurs="0" name="packageId" type="xs:string"/>
            <xs:element minOccurs="0" name="packageName" type="xs:string"/>
            <xs:element minOccurs="0" name="packageType" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="quotaProfileBalances" nillable="true" type="tns:quotaProfileBalance"/>
            <xs:element minOccurs="0" name="startTime" type="xs:long"/>
            <xs:element minOccurs="0" name="usageResetTime" type="xs:long"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="quotaProfileBalance">
        <xs:sequence>
            <xs:element minOccurs="0" name="allServiceBalance" type="tns:usageInfo"/>
            <xs:element minOccurs="0" name="quotaProfileId" type="xs:string"/>
            <xs:element minOccurs="0" name="quotaProfileName" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="usageInfos" nillable="true" type="tns:usageInfo"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="usageInfo">
        <xs:sequence>
            <xs:element minOccurs="0" name="aggregationKey" type="xs:string"/>
            <xs:element minOccurs="0" name="balance" type="tns:usage"/>
            <xs:element minOccurs="0" name="curretUsage" type="tns:usage"/>
            <xs:element minOccurs="0" name="HSQLimit" type="tns:usage"/>
            <xs:element minOccurs="0" name="serviceId" type="xs:string"/>
            <xs:element minOccurs="0" name="serviceName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="usage">
        <xs:sequence>
            <xs:element minOccurs="0" name="downloadOctets" type="xs:long"/>
            <xs:element minOccurs="0" name="time" type="xs:long"/>
            <xs:element minOccurs="0" name="totalOctets" type="xs:long"/>
            <xs:element minOccurs="0" name="uploadOctets" type="xs:long"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="balanceEnquiryResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
            <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
            <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
            <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="subscriptionInformations" nillable="true" type="tns:subscriptionInformationData"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="subscriptionState">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SUBSCRIBED"/>
            <xs:enumeration value="START_SCHEDULED"/>
            <xs:enumeration value="STARTED"/>
            <xs:enumeration value="EXPIRY_SCHEDULED"/>
            <xs:enumeration value="EXPIRED"/>
            <xs:enumeration value="UNSUBSCRIBED"/>
            <xs:enumeration value="APPROVAL_PENDING"/>
            <xs:enumeration value="REJECTED"/>
            <xs:enumeration value="UNPROCESSED"/>
            <xs:enumeration value="ACTIVE"/>
            <xs:enumeration value="STOP"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>