<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://api.act.com/"
           attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://api.act.com/"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="wsAddServiceToAccount">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actionItem" type="xs:string" form="unqualified"/>
                <xs:element name="requestId" type="xs:string" form="unqualified" />
                <xs:element name="userName" type="xs:string" form="unqualified"/>
                <xs:element name="serviceId" type="xs:string" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="wsAddServiceToAccountResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="AddServiceToAccount">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="requestId" type="xs:string" />
                            <xs:element name="responeCode" type="xs:int" />
                            <xs:element name="responseMessage" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="AddServiceToAccount">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actionItem" type="xs:string" form="unqualified"/>
                <xs:element name="requestId" type="xs:string" form="unqualified" />
                <xs:element name="userName" type="xs:string" form="unqualified"/>
                <xs:element name="serviceId" type="xs:string" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="AddServiceToAccountResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="AddServiceToAccount">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="requestId" type="xs:string" />
                            <xs:element name="responeCode" type="xs:int" />
                            <xs:element name="responseMessage" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>