<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ns="http://api.act.com/"
           targetNamespace="http://api.act.com/"
           elementFormDefault="qualified">

    <!-- Request Element Definition -->
    <xs:element name="wsGetBalance">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="alternateId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="packageId" type="xs:long" minOccurs="0" form="unqualified"/>
                <xs:element name="packageName" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="subscriptionId" type="xs:long" minOccurs="0" form="unqualified"/>
                <xs:element name="parameter1" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="parameter2" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Response Element Definition -->
    <xs:element name="wsGetBalanceResponse">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="ns:wsBalanceEnquiryResponse"/>
                <xs:element ref="ns:wsBalanceEnquiryErrorResponse"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="wsBalanceEnquiryResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="getBalance">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="parameter1" type="xs:string" minOccurs="0"/>
                            <xs:element name="parameter2" type="xs:string" minOccurs="0"/>
                            <xs:element name="responseCode" type="xs:int" minOccurs="0"/>
                            <xs:element name="responseMessage" type="xs:string" minOccurs="0"/>
                            <xs:element name="requestId" type="xs:string" minOccurs="0"/>

                            <!-- Subscription Information -->
                            <xs:element name="subscriptionInfo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="packageId" type="xs:string" minOccurs="0"/>
                                        <xs:element name="packageName" type="xs:string" minOccurs="0"/>
                                        <xs:element name="packageType" type="xs:string" minOccurs="0"/>

                                        <!-- Quota Profile Balances -->
                                        <xs:element name="quotaProfileBalances">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="allServiceBalance">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="aggregationKey" type="xs:string" minOccurs="0"/>
                                                                <xs:element name="balance">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="downloadOctets" type="xs:string" minOccurs="0"/>
                                                                            <xs:element name="time" type="xs:string" minOccurs="0"/>
                                                                            <xs:element name="totalOctets" type="xs:double" minOccurs="0"/>
                                                                            <xs:element name="totalOctetsLong" type="xs:long" minOccurs="0"/>
                                                                            <xs:element name="uploadOctets" type="xs:string" minOccurs="0"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="curretUsage">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="downloadOctets" type="xs:string" minOccurs="0"/>
                                                                            <xs:element name="time" type="xs:string" minOccurs="0"/>
                                                                            <xs:element name="totalOctets" type="xs:double" minOccurs="0"/>
                                                                            <xs:element name="totalOctetsLong" type="xs:long" minOccurs="0"/>
                                                                            <xs:element name="uploadOctets" type="xs:string" minOccurs="0"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="HSQLimit">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="downloadOctets" type="xs:string" minOccurs="0"/>
                                                                            <xs:element name="time" type="xs:string" minOccurs="0"/>
                                                                            <xs:element name="totalOctets" type="xs:double" minOccurs="0"/>
                                                                            <xs:element name="totalOctetsLong" type="xs:long" minOccurs="0"/>
                                                                            <xs:element name="uploadOctets" type="xs:string" minOccurs="0"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="serviceId" type="xs:string" minOccurs="0"/>
                                                                <xs:element name="serviceName" type="xs:string" minOccurs="0"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="quotaProfileId" type="xs:string" minOccurs="0"/>
                                                    <xs:element name="quotaProfileName" type="xs:string" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <!-- Carry Forward Value -->
                                        <xs:element name="carryForword" type="xs:int" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="wsBalanceEnquiryErrorResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="responseCode" type="xs:int" minOccurs="0"/>
                <xs:element name="responseMessage" type="xs:string" minOccurs="0"/>
                <xs:element name="requestId" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
