<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://api.act.com/"
           xmlns:tns="http://api.act.com/">

    <xs:complexType name="updateAccountResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="requestId" type="xs:string"/>
            <xs:element name="responeCode" type="xs:int"/>
            <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


    <!-- Define the response element -->
    <xs:element name="wsUpdateAccountResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="UpdateAccount" type="tns:updateAccountResponse"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>