<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://subscription.ws.nvsmx.elitecore.com/"
           xmlns:tns="http://subscription.ws.nvsmx.elitecore.com/">

    <xs:element name="wsChangeAddOnSubscriptionResponse">
    <xs:complexType>
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="tns:subscriptionResponse"/>
        </xs:sequence>
    </xs:complexType>
    </xs:element>
    <xs:complexType name="subscriptionResponse">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="addOnSubscriptions" nillable="true"
                        type="tns:subscriptionData"/>
            <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
            <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="subscriptionData">
        <xs:sequence>
            <xs:element minOccurs="0" name="addOnId" type="xs:string"/>
            <xs:element minOccurs="0" name="addOnName" type="xs:string"/>
            <xs:element minOccurs="0" name="addOnStatus" type="tns:subscriptionState"/>
            <xs:element minOccurs="0" name="addonSubscriptionId" type="xs:string"/>
            <xs:element minOccurs="0" name="endTime" type="xs:long"/>
            <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
            <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
            <xs:element minOccurs="0" name="startTime" type="xs:long"/>
            <xs:element minOccurs="0" name="subscriberIdentity" type="xs:string"/>
            <xs:element minOccurs="0" name="usageResetTime" type="xs:long"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="subscriptionState">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SUBSCRIBED"/>
            <xs:enumeration value="START_SCHEDULED"/>
            <xs:enumeration value="STARTED"/>
            <xs:enumeration value="EXPIRY_SCHEDULED"/>
            <xs:enumeration value="EXPIRED"/>
            <xs:enumeration value="UNSUBSCRIBED"/>
            <xs:enumeration value="APPROVAL_PENDING"/>
            <xs:enumeration value="REJECTED"/>
            <xs:enumeration value="UNPROCESSED"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>