<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:sub="http://subscription.ws.nvsmx.elitecore.com/"
           targetNamespace="http://subscription.ws.nvsmx.elitecore.com/"
           elementFormDefault="qualified">

    <!-- Request -->
    <xs:element name="wsChangeAddOnSubscription">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified" />
                <xs:element name="alternateId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="updateAction" type="xs:int" minOccurs="0" form="unqualified"/>
                <xs:element name="addOnSubscriptionId" type="xs:int" minOccurs="0" form="unqualified"/>
                <xs:element name="subscriptionStatusValue" type="xs:integer" minOccurs="0" form="unqualified"/>
                <xs:element name="subscriptionStatusName" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="addOnName" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="subscriptionOrder" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="startTime" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="endTime" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="rejectReason" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="parameter1" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="parameter2" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Response -->
    <xs:element name="wsChangeAddOnSubscriptionResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="return" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="addOnSubscriptions" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="addOnId" type="xs:string" />
                                        <xs:element name="addOnName" type="xs:string" />
                                        <xs:element name="addOnStatus" type="xs:string" />
                                        <xs:element name="addonSubscriptionId" type="xs:string" />
                                        <xs:element name="endTime" type="xs:long" />
                                        <xs:element name="parameter1" type="xs:string" />
                                        <xs:element name="parameter2" type="xs:string" />
                                        <xs:element name="subscriberIdentity" type="xs:string" />
                                        <xs:element name="usageResetTime" type="xs:long" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="responseCode" type="xs:int" />
                            <xs:element name="responseMessage" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
