<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://api.act.com/"
           targetNamespace="http://api.act.com/"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="wsUserLoginStatusResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="UserLoginStatus" type="tns:userLoginStatusResponse"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="userLoginStatusResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="requestId" type="xs:string"/>
            <xs:element name="responeCode" type="xs:int"/>
            <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
            <xs:element name="result" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>