<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://api.act.com/"
           xmlns:tns="http://api.act.com/"
           elementFormDefault="qualified">

    <!-- Element definition for the request -->
    <xs:element name="wsUserLoginStatus">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="userName" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="UserLoginStatus">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="userName" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Element definition for the response -->
    <xs:element name="wsUserLoginStatusResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="UserLoginStatus">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="requestId" type="xs:string"/>
                            <xs:element name="responeCode" type="xs:int"/>
                            <xs:element name="responseMessage" type="xs:string"/>
                            <xs:element name="result" type="xs:boolean"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="UserLoginStatusResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="UserLoginStatus">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="requestId" type="xs:string"/>
                            <xs:element name="responeCode" type="xs:int"/>
                            <xs:element name="responseMessage" type="xs:string"/>
                            <xs:element name="result" type="xs:boolean"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
