package com.savbill.integrationsystem.PaymentConfig.model;


public class PaymentGatewayConfigurationConstant {

    public interface PAYMENT_GATEWAY_LIST{
        String PAYTM = "PAYTM";

        String FLUTTERWAVE = "FLUTTERWAVE";

        String ERRICSON = "ERRICSON";

        String RAZORPAY = "RAZORPAY";

        String BUDPAY = "BUDPAY";

        String PHONEPE ="PHONEPE";

        String MOMO_PAY = "MoMo Pay";

        String AIRTEL = "AIRTEL";

        String SELCOM = "SELCOM";

        String MOMO_PAY_USSD_PUSH = "MoMo Pay Ussd Push";

        String AIRTEL_USSD_PUSH = "Airtel Ussd Push";

        String PAYSTACK = "PAYSTACK";

        String WAVE_PAY = "Wave Pay";

        String ONE_PAY = "ONEPAY";

        String KBZ_PAY = "KBZPAY";

        String TRANSACTEASE = "TRANSACTEASE";

        String MPESA = "MPESA";

        String MPESA_VODACOM = "MPESA Vodacom";

        String CRDB_BANK = "CRDB Bank";
    }

    public interface PAYTM{

        String PAYMENT_GATEWAY_NAME = "PAYMENT_GATEWAY_NAME";
        String REDIRECT_CWSC_URL = "REDIRECT_CWSC_URL";
        String REDIRECT_CAPTIVE_URL = "REDIRECT_CAPTIVE_URL";
        String PAYTM_CALLBACK_URL = "PAYTM_CALLBACK_URL";
        String PAYTM_CMS_ADDRESS = "PAYTM_CMS_ADDRESS";
        String PAYTM_CHANNEL_ID = "PAYTM_CHANNEL_ID";
        String PAYTM_INDUSTRY_TYPE_ID = "PAYTM_INDUSTRY_TYPE_ID";
        String PAYTM_MERCHENT_ID = "PAYTM_MERCHENT_ID";
        String PAYTM_WEBSITE = "PAYTM_WEBSITE";
        String PAYTM_MERCHANT_KEY = "PAYTM_MERCHANT_KEY";
        String PAYTM_PAYMENT_URL = "PAYTM_PAYMENT_URL";
        String PAYTM_PAYMENT_LINK_URL = "PAYTM_PAYMENT_LINK_URL";
        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";

        String MVNO_NAME = "MVNO_NAME";

        String STAFFUSER_USERNAME = "STAFFUSER_USERNAME";

        String STAFFUSER_PASSWORD = "STAFFUSER_PASSWORD";

    }

    public interface FLUTTER_WAVE{

        String PAYMENT_GATEWAY_NAME = "PAYMENT_GATEWAY_NAME";
        String CWSC_REDIRECT_URL= "CWSC_REDIRECT_URL";
        String CAPTIVE_REDIRECT_URL = "CAPTIVE_REDIRECT_URL";
        String FLUTTERWAVE_PUBLIC_KEY = "FLUTTERWAVE_PUBLIC_KEY";

        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";

        String FLUTTERWAVE_SECRET_KEY = "FLUTTERWAVE_SECRET_KEY";

        String FLUTTERWAVE_CURRENCY = "FLUTTERWAVE_CURRENCY";

        String MVNO_NAME = "MVNO_NAME";

        String STAFFUSER_USERNAME = "STAFFUSER_USERNAME";

        String STAFFUSER_PASSWORD = "STAFFUSER_PASSWORD";


    }

    public interface MTN_ERRICSON{
        String PAYMENT_GATEWAY_NAME = "PAYMENT_GATEWAY_NAME";
    }

    public interface RAZORPAY{

        String CWSC_REDIRECT_URL= "CWSC_REDIRECT_URL";
        String CAPTIVE_REDIRECT_URL = "CAPTIVE_REDIRECT_URL";
        String RAZORPAY_CURRENCY = "RAZORPAY_CURRENCY";
        String RAZORPAY_KEY_ID = "RAZORPAY_KEY_ID";
        String RAZORPAY_CALLBACK_URL = "RAZORPAY_CALLBACK_URL";
        String RAZORPAY_SECRET_KEY = "RAZORPAY_SECRET_KEY";
        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";
        String STAFFUSER_USERNAME = "STAFFUSER_USERNAME";
        String STAFFUSER_PASSWORD = "STAFFUSER_PASSWORD";
    }


    public interface BUDPAY{

        String BUDPAY_SECRET_KEY = "BUDPAY_SECRET_KEY";
        String BUDPAY_PUBLIC_KEY = "BUDPAY_PUBLIC_KEY";

        String BUDPAY_CALLBACK_URL = "BUDPAY_CALLBACK_URL";

        String BUDPAY_REQUEST_URL = "BUDPAY_REQUEST_URL";

        String BUDPAY_REDIRECT_URL = "BUDPAY_REDIRECT_URL";

        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";

        String BUDPAY_CALLBACK_CWSC_BUY_URL = "BUDPAY_CALLBACK_CWSC_BUY_URL";
    }

    public interface PHONEPE{

        String PHONEPE_MERCHANT_ID = "PHONEPE_MERCHANT_ID";

        String PHONEPE_MERCHANT_USERID = "PHONEPE_MERCHANT_USERID";

        String PHONEPE_CALLBACK_URL = "PHONEPE_CALLBACK_URL";

        String PHONEPE_SALT_INDEX = "PHONEPE_SALT_INDEX";

        String PHONEPE_SALT_KEY = "PHONEPE_SALT_KEY";

        String PHONEPE_REDIRECT_URL = "PHONEPE_REDIRECT_URL";

        String PHONPE_REDIRECT_MODE = "PHONPE_REDIRECT_MODE";

        String PHONPE_PAYMENT_INSTRUMENT_TYPE = "PHONPE_PAYMENT_INSTRUMENT_TYPE";

        String PHONPE_GATEWAY_URL = "PHONPE_GATEWAY_URL";

        String REDIRECT_IN_SECONDS = "REDIRECT_IN_SECONDS";

        String PARTNER_REDIRECT_URL = "PARTNER_REDIRECT_URL";

    }

    public interface MOMOPE{
        String MOMOPE_GATEWAY_URL = "MOMOPE_GATEWAY_URL";
        String MOMOPE_SUBSCRIPTION_KEY = "MOMOPE_SUBSCRIPTION_KEY";
        String MOMOPE_CALLBACK_URL = "MOMOPE_CALLBACK_URL";
        String MOMOPE_TARGET_ENVIROMENT = "MOMOPE_TARGET_ENVIRONMENT";
        String MOMOPE_CURRENCY = "MOMOPE_CURRENCY";
        String MOMOPE_PAYERMESSAGE ="MOMOPE_PAYERMESSAGE";
        String MOMOPE_PAYEENOTE ="MOMOPE_PAYEENOTE";
        String MOMOPE_API_KEY = "MOMOPE_API_KEY";
        String MOMOPE_API_USER = "MOMOPE_API_USER";

        String MOMO_PAY_PREFIX = "MOMO_PAY_PREFIX";

    }

    public interface SELCOMPAY{
        String SELCOM_GATEWAY_URL = "SELCOM_GATEWAY_URL";
        String SELCOM_WEBHOOK_URL = "SELCOM_WEBHOOK_URL";
        String SELCOM_API_KEY = "SELCOM_API_KEY";
        String SELCOM_SECRET_KEY = "SELCOM_SECRET_KEY";
        String SELCOM_PAYMENT_METHODS = "SELCOM_PAYMENT_METHODS";
        String SELCOM_VENDOR = "SELCOM_VENDOR";
        String SELCOM_CURRENCY = "SELCOM_CURRENCY";
        String SELCOM_SCHEDULE_TIME = "SELCOM_SCHEDULE_TIME";

    }

    public interface AIRTEL{
        String AIRTEL_CLIENT_ID = "AIRTEL_CLIENT_ID";

        String AIRTEL_CLIENT_SECRET = "AIRTEL_CLIENT_SECRET";

        String AIRTEL_GRANT_TYPE = "AIRTEL_GRANT_TYPE";

        String AIRTEL_REFERENCE = "AIRTEL_REFERENCE";

        String AIRTEL_API_URL = "AIRTEL_API_URL";

        String COUNTRY = "COUNTRY";
        String CURRENCY = "CURRENCY";

        String AIRTEL_CWSC_CALLBACK_URL = "AIRTEL_CWSC_CALLBACK_URL";

        String AIRTEL_CWSC_CAPTIVE_URL = "AIRTEL_CWSC_CAPTIVE_URL";

        String STAFFUSER_USERNAME = "STAFFUSER_USERNAME";
        String STAFFUSER_PASSWORD = "STAFFUSER_PASSWORD";
        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";
        String SCHEDULED_CALL_TIME = "SCHEDULED_CALL_TIME";

        String AIRTEL_PREFIX = "AIRTEL_PREFIX";


    }

    public interface AUDITCONSTANT{
        String PAYWAY_VALIDATE_ACCOUNT = "PAYWAY-VALIDATE_ACCOUNT";

        String PAYWAY_LIST_PACKAGES = "PAYWAY-LIST_PACKAGES";

        String PAYWAY_ACCOUNT_BALANCE = "PAYWAY-ACCOUNT_BALANCE";

        String PAYWAY_TRANSACTION_STATUS = "PAYWAY-TRANSACTION_STATUS";

        String PAYWAY_RECONSILE_STATEMENT = "PAYWAY-RECONSILE_STATEMENT";

        String PAYWAY_UPGRADE = "PAYWAY-UPGRADE";

        String PAYWAY_NEWTX = "PAYWAY-NEWTX";

        String TRADELANCE_VALIDATE_ACCOUNT = "TRADELANCE-VALIDATE_ACCOUNT";

        String TRADELANCE_LIST_PACKAGES = "TRADELANCE-LIST_PACKAGES";

        String TRADELANCE_ACCOUNT_BALANCE = "TRADELANCE-ACCOUNT_BALANCE";

        String TRADELANCE_NEWTX = "TRADELANCE-NEWTX";

        String TRADELANCE_UPDATEWIFI = "TRADELANCE-UPDATEWIFI";

        String TRADELANCE_UPGRADE = "TRADELANCE-UPGRADE";

        String TRADELANCE_USSDPUSH = "TRADELANCE-USSDPUSH";

        String SELCOM_VALIDATION = "SELCOM-VALIDATION";

        String SELCOM_NOTIFICATION = "SELCOM-NOTIFICATION";

        String AIRTEL_REVERSE_VALID_TRANSACTION = "AIRTEL_REVERSE-VALID_TRANSACTION";

        String AIRTEL_REVERSE_PROCESS_TRANSACTION = "AIRTEL_REVERSE-PROCESS_TRANSACTION";

        String AIRTEL_REVERSE_TRANSACTION_ENQUIRY = "AIRTEL_REVERSE-TRANSACTION_ENQUIRY";

        String AIRTEL_REVERSE_BILL_FETCH = "AIRTEL_REVERSE-BILL_FETCH";

        String AIRTEL_REVERSE_LOOKUP_DETAILS = "AIRTEL_REVERSE-LOOKUP_DETAILS";

        String TIGO_PESA = "TIGO-PESA";

        String MPESA_TRANSACTION = "MPESA_TRANSACTION";

        String MPESA_VODACOM_TRANSACTION = "MPESA_VODACOM_TRANSACTION";

        String THIRD_PARTY_ADD_TO_WALLET = "THIRD_PARTY_ADD_TO_WALLET";

        String THIRD_PARTY_BUY_PLAN = "THIRD_PARTY_BUY_PLAN";

        String THIRD_PARTY_FETCH_PLAN = "THIRD_PARTY_FETCH_PLAN";

        String FIND_CUSTOMER = "FIND_CUSTOMER";

        String THIRD_PARTY_CHECK_PENDING_AMOUNT = "THIRD_PARTY_CHECK_PENDING_AMOUNT";

        String THIRD_PARTY_CHECK_TRANSACTION = "THIRD_PARTY_CHECK_TRANSACTION";

        String KRA_ETIMS_ADD_CUSTOMER = "KRA_ETIMS_ADD_CUSTOMER";

        String KRA_ETIMS_UPDATE_ITEM = "KRA_ETIMS_UPDATE_ITEM";

        String KRA_ETIMS_ADD_SALE = "KRA_ETIMS_ADD_SALE";

        String KRA_ETIMS_ADD_CREDIT_NOTE = "KRA_ETIMS_ADD_CREDIT_NOTE";

        String KRA_ETIMS_ADD_ITEMS_LIST = "KRA_ETIMS_ADD_ITEMS_LIST";


        String CRDB_TRANSACTION = "CRDB_TRANSACTION";

    }

    public interface WAVEMONEY{
        String WAVEMONEY_MERCHANTID = "WAVEMONEY_MERCHANTID";
        String WAVEMONEY_GATEWAY_URL = "WAVEMONEY_GATEWAY_URL";
        String WAVEMONEY_CALLBACK_URL = "WAVEMONEY_CALLBACK_URL";
        String WAVEMONEY_SECRET_KEY = "WAVEMONEY_SECRET_KEY";
        String WAVEMONEY_CURRENCY = "WAVEMONEY_CURRENCY";
        String WAVEMONEY_REDIRECT_URL = "WAVEMONEY_REDIRECT_URL";
        String WAVEMONEY_SCHEDULE_TIME = "WAVEMONEY_SCHEDULE_TIME";
        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";
    }
    public interface PAYSTACK{
        String PAYSTACK_REQUEST_URL = "PAYSTACK_REQUEST_URL";
        String PAYSTACK_SECRET_KEY = "PAYSTACK_SECRET_KEY";
        String PAYSTACK_PUBLIC_KEY = "PAYSTACK_PUBLIC_KEY";
        String PAYSTACK_REDIRECT_URL = "PAYSTACK_REDIRECT_URL";
        String PAYSTACK_CURRENCY = "PAYSTACK_CURRENCY";
        String PAYSTACK_CALLBACK_URL ="PAYSTACK_CALLBACK_URL";
        String PAYSTACK_VERIFY_URL = "PAYSTACK_VERIFY_URL";
        String PAYSTACK_SCHEDULE_TIME = "PAYSTACK_SCHEDULE_TIME";
        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";
    }

    public interface KBZPAY{
        String KBZPAY_MERCHANT_CODE = "KBZPAY_MERCHANT_CODE";
        String KBZPAY_GATEWAY_URL = "KBZPAY_GATEWAY_URL";
        String KBZPAY_APP_ID = "KBZPAY_APP_ID";
        String KBZPAY_CALLBACK_URL = "KBZPAY_CALLBACK_URL";
        String KBZPAY_CURRENCY = "KBZPAY_CURRENCY";
        String KBZPAY_APP_KEY = "KBZPAY_APP_KEY";
        String KBZPAY_SCHEDULE_TIME = "KBZPAY_SCHEDULE_TIME";
        String KBZPAY_PAYMENT_URL = "KBZPAY_PAYMENT_URL";
        String SAVBILL_DOMAIN_URL = "SAVBILL_DOMAIN_URL";
        String KBZPAY_REDIRECT_URL = "KBZPAY_REDIRECT_URL";
        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";
    }

    public interface ONEPAY{
        String ONEPAY_MERCHANTID = "ONEPAY_MERCHANTID";
        String ONEYPAY_GATEWAY_URL = "ONEPAY_GATEWAY_URL";
        String ONEYPAY_CALLBACK_URL = "ONEPAY_CALLBACK_URL";
        String ONEYPAY_SECRET_KEY = "ONEPAY_SECRET_KEY";
        String ONEYPAY_CURRENCY = "ONEPAY_CURRENCY";
        String ONEYPAY_SCHEDULE_TIME = "ONEPAY_SCHEDULE_TIME";
        String ONEPAY_CHANNEL = "ONEPAY_CHANNEL";

    }

    public interface TRANSACTEASEPAY{
        String TRANSACTEASE_SECRET_KEY = "TRANSACTEASE_SECRET_KEY";
        String TRANSACTEASE_REQUEST_URL = "TRANSACTEASE_REQUEST_URL";
        String TRANSACTEASE_MERCHANT_ID = "TRANSACTEASE_MERCHANT_ID";
        String TRANSACTEASE_CHANNEL = "TRANSACTEASE_CHANNEL";
        String TRANSACTEASE_ACCESS_KEY = "TRANSACTEASE_ACCESS_KEY";
        String TRANSACTEASE_ALLOWED_PAYMENT_METHOD ="TRANSACTEASE_ALLOWED_PAYMENT_METHOD";
        String TRANSACTEASE_CLIENT_CREDENTIALS = "TRANSACTEASE_CLIENT_CREDENTIALS";
        String TRANSACTEASE_EXPIRED_TIME_IN_SECONDS = "TRANSACTEASE_EXPIRED_TIME_IN_SECONDS";
        String TRANSACTEASE_CALLBACK_URL = "TRANSACTEASE_CALLBACK_URL";
        String TRANSACTEASE_INS_ID = "TRANSACTEASE_INS_ID";
        String MERCHANTNAME = "TRANSACTEASE";
        String TRANSACTEASE_SCHEDULE_TIME = "TRANSACTEASE_SCHEDULE_TIME";
        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";
        String TRANSACTEASE_REDIRECT_URL = "TRANSACTEASE_REDIRECT_URL";
        String TRANSACTEASE_CURRENCY = "TRANSACTEASE_CURRENCY";
        String TRANSACTEASE_CLIENTSECRET= "TRANSACTEASE_CLIENTSECRET";
        String TRANSACTEASE_COUNTRY = "TRANSACTEASE_COUNTRY";
    }

    public interface MPESA{
        String MPESA_REQUEST_URL = "MPESA_REQUEST_URL";
        String MPESA_CONSUMER_KEY = "MPESA_CONSUMER_KEY";
        String MPESA_CONSUMER_SECRET = "MPESA_CONSUMER_SECRET";
        String MPESA_SCHEDULE_TIME = "MPESA_SCHEDULE_TIME";
        String MPESA_PARTY_A = "MPESA_PARTY_A";
        String MPESA_COMMAND_ID = "MPESA_COMMAND_ID";
        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";
        String MPESA_QUEUE_TIMEOUT_URL = "MPESA_QUEUE_TIMEOUT_URL";
        String MPESA_RESULT_URL = "MPESA_RESULT_URL";
        String MPESA_CERTIFICATE_PATH = "MPESA_CERTIFICATE_PATH";
        String MPESA_C2B_CALLBACK_URL = "MPESA_EXPRESS_SIMULATE_CALLBACK_URL";
        String MPESA_PASSKEY = "MPESA_PASSKEY";
        String EXPRESS_SIMULATE_TRANSACTION_TYPE = "EXPRESS_SIMULATE_TRANSACTION_TYPE";
        String QR_CODE_TRANSACTION_TYPE = "QR_CODE_TRANSACTION_TYPE";
        String CWSC_REDIRECT_URL = "CWSC_REDIRECT_URL";
        String MPESA_EXPRESS_PARTY_B = "MPESA_EXPRESS_PARTY_B";
        String MPESA_INITIATOR_PASSWORD="MPESA_INITIATOR_PASSWORD";
        String MPESA_INITIATOR_NAME="MPESA_INITIATOR_NAME";
    }

    public interface MPESA_VODACOM {
        String MPESA_VODACOM_SP_ID = "MPESA_VODACOM_SP_ID";
        String MPESA_VODACOM_SP_PASSWORD = "MPESA_VODACOM_SP_PASSWORD";
        String MPESA_VODACOM_CALLBACK_URL = "MPESA_VODACOM_CALLBACK_URL";
        String MPESA_VODACOM_CALLBACK_INITIATOR = "MPESA_VODACOM_CALLBACK_INITIATOR";
        String MPESA_VODACOM_CALLBACK_INITIATOR_PASSWORD = "MPESA_VODACOM_CALLBACK_INITIATOR_PASSWORD";
    }

}
