#server:
#  port: 30080

spring:
  application:
    name: SavbillCommonGateway-Service

  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 2
          max-interval: 10s
          multiplier: 2

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/


ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true



zuul:
  routes:
    SavbillRadius-Service:
      path: /SavbillRadius/**
      service-id: SavbillRadiusBss-Service
      strip-prefix: false

    SavbillNotification-Service:
      path: /SavbillNotification/**
      service-id: SavbillNotification-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    SavbillSalesCrmsBss-Service:
      path: /api/v1/SavbillSalesCrmsBss/**
      service-id: SavbillSalesCrmsBss-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    SavbillTaskMgmt-Service:
      path: /SavbillTaskMgmt/**
      service-id: SavbillTaskMgmt-Service
      strip-prefix: false

    SavbillIntegrationSystem-Service:
      path: /api/v1/SavbillIntegrationSystem/**
      service-id: SavbillIntegrationSystem-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    SavbillKpimanagement-Service:
      path: /api/v1/KpiManagement/**
      service-id: SavbillKpimanagement-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    SavbillSample-Service:
      path: /api/v1/SavbillSample/**
      service-id: SavbillSample-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    SavbillTicketManagement-Service:
      path: /api/v1/TicketManagement/**
      service-id: SavbillTicketManagement-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    SavbillInventoryManagement-Service:
      path: /api/v1/SavbillInventoryManagement/**
      service-id: SavbillInventoryManagement-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    SavbillCPMBss-Service:
      path: /api/v1/cpm/**
      service-id: SavbillCPMBss-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    SavbillRevenueManagement-Service:
      path: /api/v1/Revenue/**
      service-id: SavbillRevenueManagement-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin


    SavbillPartnerManagement-Service:
      path: /api/v1/pms/**
      service-id: SavbillPartnerManagement-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin


    SavbillNetConf-Service:
      path: /api/v1/SavbillNetConfManagement/**
      service-id: SavbillNetConf-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    Service-Manager:
      path: /api/v1/service-manager/**
      service-id: Service-Manager
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    Index-Coordination-Node:
      path: /api/v1/index-coordination-node/**
      service-id: index-coordination-node
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    Search-Agent:
      path: /api/v1/search-agent/**
      service-id: search-agent
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    Indexer-Agent:
      path: /api/v1/indexer-agent/**
      service-id: indexer-agent
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    Enrichment:
      path: /api/v1/enrichment/**
      service-id: enrichment-agent
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    Collection-Agent:
      path: /api/v1/collection-agent/**
      service-id: Collection-Agent
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    Enrichment-Lite:
      path: /api/v1/enrichment-lite/**
      service-id: enrichmentlite-agent
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    SavbillDiameter-Service:
      path: /SavbillDiameter/**
      service-id: SavbillDiameterBss-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    Savbill-DefaultProvision:
      path: /provisionCustomer
      url:  ${savbill.defaultprovision.scheme}://${savbill.defaultprovision.host}:${server.port}/api/v1/SavbillNetConfManagement/customer
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    Savbill-DefaultUpdate:
      path: /updateCustomer
      url: ${savbill.defaultprovision.scheme}://${savbill.defaultprovision.host}:${server.port}/api/v1/SavbillNetConfManagement/customer
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    Savbill-DefaultDeProvision:
      path: /deprovisionCustomer
      url: ${savbill.defaultprovision.scheme}://${savbill.defaultprovision.host}:${server.port}/api/v1/SavbillNetConfManagement/customer
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    Log-Search-Agent:
      path: /api/v1/log-search-agent/**
      service-id: log-search-agent
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

    Log-Writer-Agent:
      path: /api/v1/log-writer-agent/**
      service-id: log-writer-agent
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin


    SavbillTaskManagement-Service:
      path: /api/v1/TaskManagement/**
      service-id: SavbillTaskManagement-Service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin


    TELCOOcsEngineBss-Service:
       path: /api/v1/ocs/**
       service-id: TELCOOcsEngineBss-Service
       strip-prefix: false
       sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

