<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:api="http://api.act.com/"
           targetNamespace="http://api.act.com/"
           elementFormDefault="qualified">

    <!-- Definition for the wsGetUserSessionRequest -->
    <xs:element name="wsGetUserUsageSummary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Definition for the wsGetUserSessionResponse -->
    <xs:element name="wsGetUserUsageSummaryResponse">
        <xs:complexType>
            <xs:sequence>
                 <xs:element name="GetUserUsageSummary">
                      <xs:complexType>
                           <xs:sequence>
                            <xs:element name="aggregateBytesLimit" type="xs:double" minOccurs="0"/>
                            <xs:element name="aggregateBytesLimitLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="aggregateBytesRemaining" type="xs:double" minOccurs="0"/>
                            <xs:element name="aggregateBytesRemainingLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="aggregateBytesUsed" type="xs:double" minOccurs="0"/>
                            <xs:element name="aggregateBytesUsedLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="inBytesLimit" type="xs:double" minOccurs="0"/>
                            <xs:element name="inBytesLimitLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="inBytesRemaining" type="xs:double" minOccurs="0"/>
                            <xs:element name="inBytesRemainingLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="inBytesUsed" type="xs:double" minOccurs="0"/>
                            <xs:element name="inBytesUsedLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="outBytesLimit" type="xs:double" minOccurs="0"/>
                               <xs:element name="outBytesLimitLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="outBytesRemaining" type="xs:double" minOccurs="0"/>
                               <xs:element name="outBytesRemainingLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="outBytesUsed" type="xs:double" minOccurs="0"/>
                            <xs:element name="outBytesUsedLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="packageCode" type="xs:string" minOccurs="0"/>
                            <xs:element name="packageType" type="xs:string" minOccurs="0"/>
                            <xs:element name="qodBytesLimit" type="xs:double" minOccurs="0"/>
                            <xs:element name="qodBytesLimitLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="qodBytesRemaining" type="xs:double" minOccurs="0"/>
                            <xs:element name="qodBytesRemainingLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="qodBytesUsed" type="xs:double" minOccurs="0"/>
                            <xs:element name="qodBytesUsedLong" type="xs:long" minOccurs="0"/>

                            <xs:element name="responseMessage" type="xs:string" minOccurs="0"/>
                            <xs:element name="requestId" type="xs:string" minOccurs="0"/>
                            <xs:element name="responseCode" type="xs:int" minOccurs="0"/>
                           </xs:sequence>
                      </xs:complexType>
                 </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetUserUsageSummary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Definition for the wsGetUserSessionResponse -->
    <xs:element name="GetUserUsageSummaryResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="GetUserUsageSummary">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="aggregateBytesLimit" type="xs:double" minOccurs="0"/>
                            <xs:element name="aggregateBytesLimitLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="aggregateBytesRemaining" type="xs:double" minOccurs="0"/>
                            <xs:element name="aggregateBytesRemainingLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="aggregateBytesUsed" type="xs:double" minOccurs="0"/>
                            <xs:element name="aggregateBytesUsedLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="inBytesLimit" type="xs:double" minOccurs="0"/>
                            <xs:element name="inBytesLimitLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="inBytesRemaining" type="xs:double" minOccurs="0"/>
                            <xs:element name="inBytesRemainingLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="inBytesUsed" type="xs:double" minOccurs="0"/>
                            <xs:element name="inBytesUsedLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="outBytesLimit" type="xs:double" minOccurs="0"/>
                            <xs:element name="outBytesLimitLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="outBytesRemaining" type="xs:double" minOccurs="0"/>
                            <xs:element name="outBytesRemainingLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="outBytesUsed" type="xs:double" minOccurs="0"/>
                            <xs:element name="outBytesUsedLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="packageCode" type="xs:string" minOccurs="0"/>
                            <xs:element name="packageType" type="xs:string" minOccurs="0"/>
                            <xs:element name="qodBytesLimit" type="xs:double" minOccurs="0"/>
                            <xs:element name="qodBytesLimitLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="qodBytesRemaining" type="xs:double" minOccurs="0"/>
                            <xs:element name="qodBytesRemainingLong" type="xs:long" minOccurs="0"/>
                            <xs:element name="qodBytesUsed" type="xs:double" minOccurs="0"/>
                            <xs:element name="qodBytesUsedLong" type="xs:long" minOccurs="0"/>

                            <xs:element name="responseMessage" type="xs:string" minOccurs="0"/>
                            <xs:element name="requestId" type="xs:string" minOccurs="0"/>
                            <xs:element name="responseCode" type="xs:int" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
