<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://api.act.com/"
           xmlns:tns="http://api.act.com/">

    <xs:element name="wsGetUserUsageSummaryResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="GetUserUsageSummary" type="tns:getUserUsageSummaryResponse"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="getUserUsageSummaryResponse">
        <xs:sequence>
            <xs:element name="aggregateBytesLimit" type="xs:long"/>
            <xs:element name="aggregateBytesRemaining" type="xs:long"/>
            <xs:element name="aggregateBytesUsed" type="xs:long"/>
            <xs:element name="inBytesLimit" type="xs:long"/>
            <xs:element name="inBytesRemaining" type="xs:long"/>
            <xs:element name="inBytesUsed" type="xs:long"/>
            <xs:element name="outBytesLimit" type="xs:long"/>
            <xs:element name="outBytesRemaining" type="xs:long"/>
            <xs:element name="outBytesUsed" type="xs:long"/>
            <xs:element minOccurs="0" name="packageCode" type="xs:string"/>
            <xs:element minOccurs="0" name="packageType" type="xs:string"/>
            <xs:element name="qodBytesLimit" type="xs:long"/>
            <xs:element name="qodBytesRemaining" type="xs:long"/>
            <xs:element name="qodBytesUsed" type="xs:long"/>
            <xs:element minOccurs="0" name="requestId" type="xs:string"/>
            <xs:element name="responseCode" type="xs:int"/>
            <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


</xs:schema>