<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           targetNamespace="http://subscription.ws.nvsmx.elitecore.com/"
           xmlns="http://subscription.ws.nvsmx.elitecore.com/"
           elementFormDefault="qualified">

    <!-- Request Element -->
    <xs:element name="wsSubscribeAddOn">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="parentId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="alternateId" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="updateAction" type="xs:int" minOccurs="0" form="unqualified"/>
                <xs:element name="cui" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="addOnPackageId" type="xs:int" minOccurs="0" form="unqualified"/>
                <xs:element name="addOnPackageName" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="subscriptionStatusValue" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="subscriptionStatusName" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="startTime" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="endTime" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="parameter1" type="xs:string" minOccurs="0" form="unqualified"/>
                <xs:element name="parameter2" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Response Element -->
    <xs:element name="wsSubscribeAddOnResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="return">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="responseCode" type="xs:int" />
                            <xs:element name="responseMessage" type="xs:string" />
                            <xs:element name="addOnSubscriptions" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="endTime" type="xs:string" />
                                        <xs:element name="parameter1" type="xs:string" minOccurs="0" />
                                        <xs:element name="parameter2" type="xs:string" minOccurs="0" />
                                        <xs:element name="startTime" type="xs:string" />
                                        <xs:element name="subscriberIdentity" type="xs:string" />
                                        <xs:element name="addOnId" type="xs:string" />
                                        <xs:element name="addOnName" type="xs:string" />
                                        <xs:element name="addOnStatus" type="xs:string" />
                                        <xs:element name="addOnSubscriptionId" type="xs:string" />
                                        <xs:element name="usageResetTime" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
