<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
           xmlns:npm="http://npm.redback.com"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           targetNamespace="http://npm.redback.com"
           elementFormDefault="qualified">

    <!-- Request XML schema definition -->
    <xs:element name="getSubscriberAccountXML">
        <xs:complexType>
            <xs:sequence>
                <!-- Updated element with xsi:type -->
                <xs:element name="String_1" type="xs:string" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="getSubscriberAccountXMLResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="result" type="xs:string" minOccurs="0" form="unqualified"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
