<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           targetNamespace="http://subscription.ws.nvsmx.elitecore.com/"
           xmlns="http://subscription.ws.nvsmx.elitecore.com/"
           elementFormDefault="qualified">

    <!-- Request Element -->
    <xs:element name="wsChangeTopUpSubscription">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" form="unqualified" name="subscriberId" type="xs:string"/>
                <xs:element minOccurs="0" form="unqualified" name="alternateId" type="xs:string"/>
                <xs:element minOccurs="0" form="unqualified" name="updateAction" type="xs:string"/>
                <xs:element minOccurs="0" form="unqualified" name="topUpSubscriptionId" type="xs:int"/>
                <xs:element minOccurs="0" form="unqualified" name="subscriptionStatusValue" type="xs:string"/>
                <xs:element minOccurs="0" form="unqualified" name="subscriptionStatusName" type="xs:string"/>
                <xs:element minOccurs="0" form="unqualified" name="topUpName" type="xs:string"/>
                <xs:element minOccurs="0" form="unqualified" name="subscriptionOrder" type="xs:string"/>
                <xs:element minOccurs="0" form="unqualified" name="startTime" type="xs:string"/>
                <xs:element minOccurs="0" form="unqualified" name="endTime" type="xs:string"/>
                <xs:element minOccurs="0" form="unqualified" name="rejectReason" type="xs:string"/>
                <xs:element minOccurs="0" form="unqualified" name="parameter1" type="xs:string"/>
                <xs:element minOccurs="0" form="unqualified" name="parameter2" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Response Element -->
    <xs:element name="wsChangeTopUpSubscriptionResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="return">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="responseCode" type="xs:int" />
                            <xs:element name="responseMessage" type="xs:string" />
                            <xs:element name="topUpSubscriptions">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="endTime" type="xs:long" />
                                        <xs:element name="subscriberIdentity" type="xs:string" />
                                        <xs:element name="topUpId" type="xs:string" />
                                        <xs:element name="topUpName" type="xs:string" />
                                        <xs:element name="topUpStatus" type="xs:string" />
                                        <xs:element name="topUpSubscriptionId" type="xs:string" />
                                        <xs:element name="usageResetTime" type="xs:long" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
