server:
  port: ${PORT:9090}

#http:
  #port: ${PORT:9090}

spring:  
  application:
    name: SavbillRadiusBss-Service

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
