<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://api.act.com/"
           targetNamespace="http://api.act.com/" elementFormDefault="qualified">

<!--    <xs:element name="addAccountRequest">-->
<!--        <xs:complexType>-->
<!--            <xs:sequence>-->
<!--                <xs:element name="actionItem" type="xs:string" />-->
<!--                <xs:element name="requestId" type="xs:string"/>-->
<!--                <xs:element name="userName" type="xs:string"/>-->
<!--                <xs:element name="password" type="xs:string"/>-->
<!--                <xs:element name="serviceId" type="xs:string"/>-->
<!--            </xs:sequence>-->
<!--        </xs:complexType>-->
<!--    </xs:element>-->

<!--    <xs:element name="addAccountResponse">-->
<!--        <xs:complexType>-->
<!--            <xs:sequence>-->
<!--                <xs:element name="requestId" type="xs:string"/>-->
<!--                <xs:element name="responseCode" type="xs:string"/>-->
<!--                <xs:element name="responseMessage" type="xs:string"/>-->
<!--            </xs:sequence>-->
<!--        </xs:complexType>-->
<!--    </xs:element>-->
</xs:schema>
