server:
  port: ${PORT:30081}

spring:  
  application:
    name: SavbillRevenueManagement-Service
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 2
          max-interval: 10s
          multiplier: 2

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
