log4j.rootLogger=DEBUG, file, console

log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=log/savbill-revenue.log
log4j.appender.file.MaxFileSize=100MB
log4j.appender.file.MaxBackupIndex=10
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern={"level":"%p", "user":"%X{userName}", "traceId":"%X{traceId}", "spanId":"%X{spanId}", "type":"%X{type}","timestamp":"%d{ISO8601}", "module":"Savbill-Revenue-Management","thread":"%t","sub-module":"%F", "line":"%L","message":"%m"}%n

log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern={"level":"%p", "user":"%X{userName}", "traceId":"%X{traceId}", "spanId":"%X{spanId}", "type":"%X{type}","timestamp":"%d{ISO8601}", "module":"Savbill-Revenue-Management","thread":"%t","sub-module":"%F", "line":"%L","message":"%m"}%n

log4j.logger.commonlog=DEBUG, commonlog
log4j.additivity.commonlog=false
log4j.appender.commonlog=org.apache.log4j.RollingFileAppender
log4j.appender.commonlog.File=SavbillWifiServer.log
log4j.appender.commonlog.MaxFileSize=100MB
log4j.appender.commonlog.MaxBackupIndex=10
log4j.appender.commonlog.layout=org.apache.log4j.PatternLayout
log4j.appender.commonlog.layout.ConversionPattern={"level":"%p", "user":"%X{userName}", "trace-id":"%X{traceId}", "span-id":"%X{spanId}", "type":"%X{type}","timestamp":"%d{ISO8601}", "module":"Savbill-wifi","thread":"%t","sub-module":"%F", "line":"%L","message":"%m"}%n

log4j.logger.io.swagger.models.parameters.AbstractSerializableParameter=error



# Logger for PrepaidInvoiceService
log4j.logger.prepaid.service.core.com.savbill.revenuemanagement.PrepaidInvoiceService=DEBUG, invoiceAppender
log4j.additivity.prepaid.service.core.com.savbill.revenuemanagement.PrepaidInvoiceService=false


# Logger for PostpaidInvoiceService
log4j.logger.postpaid.service.core.com.savbill.revenuemanagement.PostpaidInvoiceService=DEBUG, invoiceAppender
log4j.additivity.postpaid.service.core.com.savbill.revenuemanagement.PostpaidInvoiceService=false


# Logger for InvoiceUtil
log4j.logger.common.service.core.com.savbill.revenuemanagement.InvoiceUtil=DEBUG, invoiceAppender
log4j.additivity.common.service.core.com.savbill.revenuemanagement.InvoiceUtil=false

# Logger for TaxService
log4j.logger.service.Tax.productmanagement.com.savbill.revenuemanagement.TaxService=DEBUG, invoiceAppender
log4j.additivity.service.Tax.productmanagement.com.savbill.revenuemanagement.TaxService=false\
  
# Logger for PostPaidInvoiceUtil
log4j.logger.postpaid.service.core.com.savbill.revenuemanagement.PostPaidInvoiceUtil=DEBUG, invoiceAppender
log4j.additivity.postpaid.service.core.com.savbill.revenuemanagement.PostPaidInvoiceUtil=false

# Logger for SubscriberService
log4j.logger.customers.entity.core.com.savbill.revenuemanagement.SubscriberService=DEBUG, invoiceAppender
log4j.additivity.customers.entity.core.com.savbill.revenuemanagement.SubscriberService=false



# Logger for PostPaidInvoiceUtil
log4j.logger.rabbitmq.com.savbill.revenuemanagement.MessageReceiver=DEBUG, invoiceAppender
log4j.additivity.rabbitmq.com.savbill.revenuemanagement.MessageReceiver=false



# Appender for CustomersService logs with the new pattern
log4j.appender.invoiceAppender=org.apache.log4j.RollingFileAppender
log4j.appender.invoiceAppender.File=log/invoiceCreation.log
log4j.appender.invoiceAppender.MaxFileSize=100MB
log4j.appender.invoiceAppender.MaxBackupIndex=10
log4j.appender.invoiceAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.invoiceAppender.layout.ConversionPattern=%d{ISO8601} [%t] %-5p %c{1}.%L - %X{correlationId} %X{userId} - %m%n
