package com.diameter.commons;

public enum ConnectionEvents {
  CONNECTION_ESTABLISHED, CONNECTION_BREAK, DISCONNECTED, CONNECTION_DPR, SHUTDOWN, FORCE_CLOSE, REJECT_CONNECTION, TIMER_EXPIRED, HANDSHAKE_FAIL, CONNECTION_FAILURE, CONNECTION_CREATED;
}

