<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://elitecore.com/ActApi/soap"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:ns2="http://schemas.xmlsoap.org/soap/http"
                  xmlns:ns1="http://api.act.com/"
                  name="QodOperations"
                  targetNamespace="http://elitecore.com/ActApi/soap">

    <wsdl:import location="http://localhost:41080/new-api/QodServices/finalAppWsdl.wsdl"
                 namespace="http://api.act.com/">
    </wsdl:import>
    <wsdl:binding name="QodOperationsSoapBinding" type="ns1:QodSubscriberOperation">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="LogoffUserSessions">
            <soap:operation soapAction="http://elitecore.com/soap/LogoffUserSessions" style="document"/>
            <wsdl:input name="LogoffUserSessions">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="LogoffUserSessionsResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetAccountDetails">
            <soap:operation soapAction="http://elitecore.com/soap/GetAccountDetails" style="document"/>
            <wsdl:input name="GetAccountDetails">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="GetAccountDetailsResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>


        <wsdl:operation name="AuthenticateUser">
            <soap:operation soapAction="http://elitecore.com/soap/AuthenticateUser" style="document"/>
            <wsdl:input name="AuthenticateUser">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="AuthenticateUserResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>


        <wsdl:operation name="AddAccount">
            <soap:operation soapAction="http://elitecore.com/soap/AddAccount" style="document"/>
            <wsdl:input name="AddAccount">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="AddAccountResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetUserUsageSummary">
            <soap:operation soapAction="http://elitecore.com/soap/GetUserUsageSummary" style="document"/>
            <wsdl:input name="GetUserUsageSummary">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="GetUserUsageSummaryResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>


        <wsdl:operation name="ChangeService">
            <soap:operation soapAction="http://elitecore.com/soap/ChangeService" style="document"/>
            <wsdl:input name="ChangeService">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="ChangeServiceResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="RemoveAccount">
            <soap:operation soapAction="http://elitecore.com/soap/RemoveAccount" style="document"/>
            <wsdl:input name="RemoveAccount">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="RemoveAccountResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="ResetUsageForAccount">
            <soap:operation soapAction="http://elitecore.com/soap/ResetUsageForAccount" style="document"/>
            <wsdl:input name="ResetUsageForAccount">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="ResetUsageForAccountResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="LoginSession">
            <soap:operation soapAction="http://elitecore.com/soap/LoginSession" style="document"/>
            <wsdl:input name="LoginSession">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="LoginSessionResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetAccountName">
            <soap:operation soapAction="http://elitecore.com/soap/GetAccountName" style="document"/>
            <wsdl:input name="GetAccountName">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="GetAccountNameResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="AddServiceToAccount">
            <soap:operation soapAction="http://elitecore.com/soap/AddServiceToAccount" style="document"/>
            <wsdl:input name="AddServiceToAccount">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="AddServiceToAccountResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="SessionLoginStatus">
            <soap:operation soapAction="http://elitecore.com/soap/SessionLoginStatus" style="document"/>
            <wsdl:input name="SessionLoginStatus">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="SessionLoginStatusResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="UpdateAccount">
            <soap:operation soapAction="http://elitecore.com/soap/UpdateAccount" style="document"/>
            <wsdl:input name="UpdateAccount">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="UpdateAccountResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="UpdateUserUsage">
            <soap:operation soapAction="http://elitecore.com/soap/UpdateUserUsage" style="document"/>
            <wsdl:input name="UpdateUserUsage">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="UpdateUserUsageResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="UserLoginStatus">
            <soap:operation soapAction="http://elitecore.com/soap/UserLoginStatus" style="document"/>
            <wsdl:input name="UserLoginStatus">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="UserLoginStatusResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetBalance">
            <soap:operation soapAction="http://elitecore.com/soap/GetBalance" style="document"/>
            <wsdl:input name="GetBalance">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="BalanceEnquiryResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetUserSession">
            <soap:operation soapAction="http://elitecore.com/soap/GetUserSession" style="document"/>
            <wsdl:input name="GetUserSession">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="GetUserSessionResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="LogoffUserSession">
            <soap:operation soapAction="http://elitecore.com/soap/LogoffUserSession" style="document"/>
            <wsdl:input name="LogoffUserSession">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="LogoffUserSessionResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

    </wsdl:binding>


    <!-- Service definition -->
    <wsdl:service name="QodOperations">
        <wsdl:port binding="tns:QodOperationsSoapBinding" name="QodOperationsService">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


</wsdl:definitions>
