<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:ns1="http://subscription.ws.nvsmx.elitecore.com/"
                  xmlns:ses="http://sessionmanagement.ws.nvsmx.elitecore.com/"
                  name="SubscriptionWS"
                  targetNamespace="http://subscription.ws.nvsmx.elitecore.com/">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://subscription.ws.nvsmx.elitecore.com/"
                   elementFormDefault="unqualified" targetNamespace="http://subscription.ws.nvsmx.elitecore.com/"
                   version="1.0">
            <xs:element name="wsSubscribeTopUp" type="tns:wsSubscribeTopUp"/>
            <xs:element name="wsSubscribeTopUpResponse" type="tns:wsSubscribeTopUpResponse"/>
            <xs:element name="wsSubscribeAddOn" type="tns:wsSubscribeAddOn"/>
            <xs:element name="wsSubscribeAddOnResponse" type="tns:wsSubscribeAddOnResponse"/>
            <xs:element name="wsChangeTopUpSubscription" type="tns:wsChangeTopUpSubscription"/>
            <xs:element name="wsChangeTopUpSubscriptionResponse" type="tns:wsChangeTopUpSubscriptionResponse"/>
            <xs:element name="wsChangeAddOnSubscription" type="tns:wsChangeAddOnSubscription"/>
            <xs:element name="wsChangeAddOnSubscriptionResponse" type="tns:wsChangeAddOnSubscriptionResponse"/>
            <xs:element name="wsGetBalance" type="tns:wsGetBalance"/>
            <xs:element name="wsGetBalanceResponse" type="tns:wsGetBalanceResponse"/>

            <xs:complexType name="wsSubscribeTopUp">
                <xs:sequence>
                    <xs:element minOccurs="0" name="parentId" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="updateAction" type="xs:string"/>
                    <xs:element minOccurs="0" name="cui" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpPackageId" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpPackageName" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusValue" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusName" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsSubscribeTopUpResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="tns:topUpSubscriptionResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="topUpSubscriptionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="topUpSubscriptions" nillable="true"
                                type="tns:topUpSubscriptionData"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="topUpSubscriptionData">
                <xs:sequence>
                    <xs:element minOccurs="0" name="endTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="subscriberIdentity" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpId" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpName" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpStatus" type="tns:subscriptionState"/>
                    <xs:element minOccurs="0" name="topUpSubscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="usageResetTime" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
            <xs:simpleType name="subscriptionState">
                <xs:restriction base="xs:string">
                    <xs:enumeration value="SUBSCRIBED"/>
                    <xs:enumeration value="START_SCHEDULED"/>
                    <xs:enumeration value="STARTED"/>
                    <xs:enumeration value="EXPIRY_SCHEDULED"/>
                    <xs:enumeration value="EXPIRED"/>
                    <xs:enumeration value="UNSUBSCRIBED"/>
                    <xs:enumeration value="APPROVAL_PENDING"/>
                    <xs:enumeration value="REJECTED"/>
                    <xs:enumeration value="UNPROCESSED"/>
                    <xs:enumeration value="ACTIVE"/>
                    <xs:enumeration value="STOP"/>
                </xs:restriction>
            </xs:simpleType>

            <xs:complexType name="wsSubscribeAddOn">
                <xs:sequence>
                    <xs:element minOccurs="0" name="parentId" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="updateAction" type="xs:string"/>
                    <xs:element minOccurs="0" name="cui" type="xs:string"/>
                    <xs:element minOccurs="0" name="addOnPackageId" type="xs:string"/>
                    <xs:element minOccurs="0" name="addOnPackageName" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusValue" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusName" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsSubscribeAddOnResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="tns:subscriptionResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="subscriptionResponse">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="addOnSubscriptions" nillable="true"
                                type="tns:subscriptionData"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="subscriptionData">
                <xs:sequence>
                    <xs:element minOccurs="0" name="addOnId" type="xs:string"/>
                    <xs:element minOccurs="0" name="addOnName" type="xs:string"/>
                    <xs:element minOccurs="0" name="addOnStatus" type="tns:subscriptionState"/>
                    <xs:element minOccurs="0" name="addonSubscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="subscriberIdentity" type="xs:string"/>
                    <xs:element minOccurs="0" name="usageResetTime" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsChangeTopUpSubscription">
                <xs:sequence>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="updateAction" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpSubscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusValue" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusName" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpName" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionOrder" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="rejectReason" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsChangeTopUpSubscriptionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="tns:topUpSubscriptionResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="topUpSubscriptionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="topUpSubscriptions" nillable="true"
                                type="tns:topUpSubscriptionData"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsChangeAddOnSubscription">
                <xs:sequence>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="updateAction" type="xs:string"/>
                    <xs:element minOccurs="0" name="addOnSubscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusValue" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusName" type="xs:string"/>
                    <xs:element minOccurs="0" name="addOnName" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionOrder" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="rejectReason" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsChangeAddOnSubscriptionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="tns:subscriptionResponse"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsGetBalance">
                <xs:sequence>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageId" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageName" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsGetBalanceResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="tns:balanceEnquiryResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="balanceEnquiryResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="subscriptionInformations" nillable="true" type="tns:subscriptionInformationData"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="subscriptionInformationData">
                <xs:sequence>
                    <xs:element minOccurs="0" name="addOnStatus" type="tns:subscriptionState"/>
                    <xs:element minOccurs="0" name="addonSubscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="packageDescription" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageId" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageName" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageType" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="quotaProfileBalances" nillable="true" type="tns:quotaProfileBalance"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="usageResetTime" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
            <xs:simpleType name="subscriptionState">
                <xs:restriction base="xs:string">
                    <xs:enumeration value="SUBSCRIBED"/>
                    <xs:enumeration value="START_SCHEDULED"/>
                    <xs:enumeration value="STARTED"/>
                    <xs:enumeration value="EXPIRY_SCHEDULED"/>
                    <xs:enumeration value="EXPIRED"/>
                    <xs:enumeration value="UNSUBSCRIBED"/>
                    <xs:enumeration value="APPROVAL_PENDING"/>
                    <xs:enumeration value="REJECTED"/>
                    <xs:enumeration value="UNPROCESSED"/>
                    <xs:enumeration value="ACTIVE"/>
                    <xs:enumeration value="STOP"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:complexType name="quotaProfileBalance">
                <xs:sequence>
                    <xs:element minOccurs="0" name="allServiceBalance" type="tns:usageInfo"/>
                    <xs:element minOccurs="0" name="quotaProfileId" type="xs:string"/>
                    <xs:element minOccurs="0" name="quotaProfileName" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="usageInfos" nillable="true" type="tns:usageInfo"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="usageInfo">
                <xs:sequence>
                    <xs:element minOccurs="0" name="aggregationKey" type="xs:string"/>
                    <xs:element minOccurs="0" name="balance" type="tns:usage"/>
                    <xs:element minOccurs="0" name="curretUsage" type="tns:usage"/>
                    <xs:element minOccurs="0" name="HSQLimit" type="tns:usage"/>
                    <xs:element minOccurs="0" name="serviceId" type="xs:string"/>
                    <xs:element minOccurs="0" name="serviceName" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="usage">
                <xs:sequence>
                    <xs:element minOccurs="0" name="downloadOctets" type="xs:long"/>
                    <xs:element minOccurs="0" name="time" type="xs:long"/>
                    <xs:element minOccurs="0" name="totalOctets" type="xs:long"/>
                    <xs:element minOccurs="0" name="uploadOctets" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>

        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   xmlns:tns="http://sessionmanagement.ws.nvsmx.elitecore.com/"
                   elementFormDefault="unqualified"
                   targetNamespace="http://sessionmanagement.ws.nvsmx.elitecore.com/"
                   version="1.0">

            <xs:element name="wsReauthSessionsBySubscriberIdentity">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="subscriberId" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="alternateId" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="parameter1" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="parameter2" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsReauthSessionsBySubscriberIdentityResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="return" type="tns:sessionReAuthResponse"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:complexType name="sessionReAuthResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>

    </wsdl:types>

    <wsdl:message name="wsSubscribeTopUpResponse">
        <wsdl:part element="ns1:wsSubscribeTopUpResponse" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsSubscribeTopUp">
        <wsdl:part element="ns1:wsSubscribeTopUp" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="wsSubscribeAddOn">
        <wsdl:part element="ns1:wsSubscribeAddOn" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsSubscribeAddOnResponse">
        <wsdl:part element="ns1:wsSubscribeAddOnResponse" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="wsChangeTopUpSubscription">
        <wsdl:part element="ns1:wsChangeTopUpSubscription" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsChangeTopUpSubscriptionResponse">
        <wsdl:part element="ns1:wsChangeTopUpSubscriptionResponse" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="wsChangeAddOnSubscription">
        <wsdl:part element="ns1:wsChangeAddOnSubscription" name="parameters"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsChangeAddOnSubscriptionResponse">
        <wsdl:part element="ns1:wsChangeAddOnSubscriptionResponse" name="parameters"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsGetBalance">
        <wsdl:part element="ns1:wsGetBalance" name="parameters"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsGetBalanceResponse">
        <wsdl:part element="ns1:wsGetBalanceResponse" name="parameters"> </wsdl:part>
    </wsdl:message>

    <wsdl:message name="wsReauthSessionsBySubscriberIdentity">
        <wsdl:part element="ses:wsReauthSessionsBySubscriberIdentity" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsReauthSessionsBySubscriberIdentityResponse">
        <wsdl:part element="ses:wsReauthSessionsBySubscriberIdentityResponse" name="parameters"></wsdl:part>
    </wsdl:message>


    <wsdl:portType name="SubscriptionWS">
        <wsdl:operation name="wsSubscribeTopUp">
            <wsdl:input message="ns1:wsSubscribeTopUp" name="wsSubscribeTopUp"></wsdl:input>
            <wsdl:output message="ns1:wsSubscribeTopUpResponse" name="wsSubscribeTopUpResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsSubscribeAddOn">
            <wsdl:input message="ns1:wsSubscribeAddOn" name="wsSubscribeAddOn"></wsdl:input>
            <wsdl:output message="ns1:wsSubscribeAddOnResponse" name="wsSubscribeAddOnResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsChangeTopUpSubscription">
            <wsdl:input message="ns1:wsChangeTopUpSubscription" name="wsChangeTopUpSubscription"></wsdl:input>
            <wsdl:output message="ns1:wsChangeTopUpSubscriptionResponse"
                         name="wsChangeTopUpSubscriptionResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsChangeAddOnSubscription">
            <wsdl:input message="ns1:wsChangeAddOnSubscription" name="wsChangeAddOnSubscription"> </wsdl:input>
            <wsdl:output message="ns1:wsChangeAddOnSubscriptionResponse" name="wsChangeAddOnSubscriptionResponse"> </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsGetBalance">
            <wsdl:input message="ns1:wsGetBalance" name="wsGetBalance"> </wsdl:input>
            <wsdl:output message="ns1:wsGetBalanceResponse" name="wsGetBalanceResponse"> </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsReauthSessionsBySubscriberIdentity">
            <wsdl:input message="ns1:wsReauthSessionsBySubscriberIdentity" name="wsReauthSessionsBySubscriberIdentity"></wsdl:input>
            <wsdl:output message="ns1:wsReauthSessionsBySubscriberIdentityResponse" name="wsReauthSessionsBySubscriberIdentityResponse"></wsdl:output>
        </wsdl:operation>
    </wsdl:portType>


</wsdl:definitions>