<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://api.act.com/"
                  xmlns:sch="http://subscription.ws.nvsmx.elitecore.com/"
                  xmlns:rch="http://sessionmanagement.ws.nvsmx.elitecore.com/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  targetNamespace="http://api.act.com/">

    <!-- First Service: wsAuthenticateUser -->
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   elementFormDefault="unqualified" xmlns:tns="http://api.act.com/"
                   targetNamespace="http://api.act.com/">

            <xs:element name="wsAuthenticateUser" type="tns:wsAuthenticateUser"/>
            <xs:element name="wsAuthenticateUserResponse" type="tns:wsAuthenticateUserResponse"/>
            <xs:element name="wsGetAccountDetails" type="tns:wsGetAccountDetails"/>
            <xs:element name="wsGetAccountDetailsResponse" type="tns:wsGetAccountDetailsResponse"/>
            <xs:element name="wsAddAccount" type="tns:wsAddAccount"/>
            <xs:element name="wsAddAccountResponse" type="tns:wsAddAccountResponse"/>
            <xs:element name="wsGetUserUsageSummary" type="tns:wsGetUserUsageSummary"/>
            <xs:element name="wsGetUserUsageSummaryResponse" type="tns:wsGetUserUsageSummaryResponse"/>
            <xs:element name="wsAddServiceToAccount" type="tns:wsAddServiceToAccount"/>
            <xs:element name="wsAddServiceToAccountResponse" type="tns:wsAddServiceToAccountResponse"/>
            <xs:element name="wsChangeService" type="tns:wsChangeService"/>
            <xs:element name="wsChangeServiceResponse" type="tns:wsChangeServiceResponse"/>
            <xs:element name="wsGetAccountName" type="tns:wsGetAccountName"/>
            <xs:element name="wsGetAccountNameResponse" type="tns:wsGetAccountNameResponse"/>
            <xs:element name="wsLoginSession" type="tns:wsLoginSession"/>
            <xs:element name="wsLoginSessionResponse" type="tns:wsLoginSessionResponse"/>
            <xs:element name="wsLogoffUserSessions" type="tns:wsLogoffUserSessions"/>
            <xs:element name="wsLogoffUserSessionsResponse" type="tns:wsLogoffUserSessionsResponse"/>
            <xs:element name="wsRemoveAccount" type="tns:wsRemoveAccount"/>
            <xs:element name="wsRemoveAccountResponse" type="tns:wsRemoveAccountResponse"/>
            <xs:element name="wsResetUsageForAccount" type="tns:wsResetUsageForAccount"/>
            <xs:element name="wsResetUsageForAccountResponse" type="tns:wsResetUsageForAccountResponse"/>
            <xs:element name="wsSessionLoginStatus" type="tns:wsSessionLoginStatus"/>
            <xs:element name="wsSessionLoginStatusResponse" type="tns:wsSessionLoginStatusResponse"/>
            <xs:element name="wsUpdateAccount" type="tns:wsUpdateAccount"/>
            <xs:element name="wsUpdateAccountResponse" type="tns:wsUpdateAccountResponse"/>
            <xs:element name="wsUpdateUserUsage" type="tns:wsUpdateUserUsage"/>
            <xs:element name="wsUpdateUserUsageResponse" type="tns:wsUpdateUserUsageResponse"/>
            <xs:element name="wsUserLoginStatus" type="tns:wsUserLoginStatus"/>
            <xs:element name="wsUserLoginStatusResponse" type="tns:wsUserLoginStatusResponse"/>
            <xs:element name="wsGetUserSession" type="tns:wsGetUserSession"/>
            <xs:element name="wsGetUserSessionResponse" type="tns:wsGetUserSessionResponse"/>
            <xs:element name="wsLogoffUserSession" type="tns:wsLogoffUserSession"/>
            <xs:element name="wsLogoffUserSessionResponse" type="tns:wsLogoffUserSessionResponse"/>
            <xs:element name="wsGetBalance" type="tns:wsGetBalance"/>
            <xs:element name="wsBalanceEnquiryResponse" type="tns:wsBalanceEnquiryResponse"/>

            <xs:complexType name="wsGetUserSession">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="ipAddress" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsGetUserSessionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="GetUserSession" type="tns:getUserSessionResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="getUserSessionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="acctSessionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="callingStationId" type="xs:string"/>
                    <xs:element minOccurs="0" name="circuitType" type="xs:string"/>
                    <xs:element minOccurs="0" name="context" type="xs:string"/>
                    <xs:element minOccurs="0" name="delegatedIpv6Prefixes" type="xs:string"/>
                    <xs:element minOccurs="0" name="framedIpv6Prefixes" type="xs:string"/>
                    <xs:element minOccurs="0" name="macAddress" type="xs:string"/>
                    <xs:element minOccurs="0" name="medium" type="xs:string"/>
                    <xs:element minOccurs="0" name="NASPortId" type="xs:string"/>
                    <xs:element minOccurs="0" name="NASPortType" type="xs:string"/>
                    <xs:element minOccurs="0" name="nasId" type="xs:string"/>
                    <xs:element minOccurs="0" name="nasType" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element minOccurs="0" name="sessionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="sessionIp" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:dateTime"/>
                    <xs:element minOccurs="0" name="subscriberAccount" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsUserLoginStatus">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsUserLoginStatusResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="UserLoginStatus" type="tns:userLoginStatusResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="userLoginStatusResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element name="result" type="xs:boolean"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsUpdateUserUsage">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                    <xs:element minOccurs="0" name="usageBytes" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsUpdateUserUsageResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="UpdateUserUsage" type="tns:updateUserUsageResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="updateUserUsageResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsLogoffUserSession">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="ipAddress" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsLogoffUserSessionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="LogoffUserSession" type="tns:logoffUserSessionResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="logoffUserSessionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element name="result" type="xs:boolean"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsAuthenticateUser">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                    <xs:element minOccurs="0" name="password" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsAuthenticateUserResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="AuthenticateUser" type="tns:authenticateUserResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="authenticateUserResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element name="result" type="xs:boolean"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsSessionLoginStatus">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="ipAddress" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsSessionLoginStatusResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="SessionLoginStatus" type="tns:sessionLoginStatusResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="sessionLoginStatusResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element name="result" type="xs:boolean"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsUpdateAccount">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="item" type="tns:subscriberMapEntry"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsUpdateAccountResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="UpdateAccount" type="tns:updateAccountResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="updateAccountResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsResetUsageForAccount">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsResetUsageForAccountResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="ResetUsageForAccount" type="tns:resetUsageForAccountResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="resetUsageForAccountResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsGetAccountDetails">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsGetAccountDetailsResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="GetAccountDetails" type="tns:getAccountDetailsResponse"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="getAccountDetailsResponse">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="item" nillable="true"
                                type="tns:subscriberMapEntry"/>
                    <xs:element minOccurs="0" name="password" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element minOccurs="0" name="serviceId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>


            <xs:complexType name="subscriberMapEntry">
                <xs:sequence>
                    <xs:element minOccurs="0" name="key" type="xs:string"/>
                    <xs:element minOccurs="0" name="value" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsAddAccount">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                    <xs:element minOccurs="0" name="password" type="xs:string"/>
                    <xs:element minOccurs="0" name="serviceId" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="item" type="tns:subscriberMapEntry"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsAddAccountResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="AddAccount" type="tns:addAccountResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="addAccountResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsGetUserUsageSummary">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsGetUserUsageSummaryResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="GetUserUsageSummary" type="tns:getUserUsageSummaryResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="getUserUsageSummaryResponse">
                <xs:sequence>
                    <xs:element name="aggregateBytesLimit" type="xs:long"/>
                    <xs:element name="aggregateBytesRemaining" type="xs:long"/>
                    <xs:element name="aggregateBytesUsed" type="xs:long"/>
                    <xs:element name="inBytesLimit" type="xs:long"/>
                    <xs:element name="inBytesRemaining" type="xs:long"/>
                    <xs:element name="inBytesUsed" type="xs:long"/>
                    <xs:element name="outBytesLimit" type="xs:long"/>
                    <xs:element name="outBytesRemaining" type="xs:long"/>
                    <xs:element name="outBytesUsed" type="xs:long"/>
                    <xs:element minOccurs="0" name="packageCode" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageType" type="xs:string"/>
                    <xs:element name="qodBytesLimit" type="xs:long"/>
                    <xs:element name="qodBytesRemaining" type="xs:long"/>
                    <xs:element name="qodBytesUsed" type="xs:long"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responseCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsAddServiceToAccount">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                    <xs:element minOccurs="0" name="serviceId" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsAddServiceToAccountResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="AddServiceToAccount" type="tns:addServiceToAccountResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="addServiceToAccountResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsChangeService">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                    <xs:element minOccurs="0" name="overrides" type="xs:string"/>
                    <xs:element minOccurs="0" name="serviceId" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsChangeServiceResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="ChangeService" type="tns:changeServiceResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="changeServiceResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsGetAccountName">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="ipAddress" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsGetAccountNameResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="GetAccountName" type="tns:getAccountNameResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="getAccountNameResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="accountName" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsRemoveAccount">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsRemoveAccountResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="RemoveAccount" type="tns:removeAccountResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="removeAccountResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsLoginSession">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="ipAddress" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                    <xs:element minOccurs="0" name="password" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsLoginSessionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="LoginSession" type="tns:loginSessionResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="loginSessionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsLogoffUserSessions">
                <xs:sequence>
                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsLogoffUserSessionsResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="LogoffUserSessions" type="tns:logoffUserSessionsResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="logoffUserSessionsResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element name="result" type="xs:boolean"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsGetBalance">
                <xs:sequence>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageId" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageName" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsBalanceEnquiryResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="getBalance" type="tns:balanceEnquiryResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="balanceEnquiryResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="subscriptionInformations" nillable="true" type="tns:subscriptionInformationData"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="subscriptionInformationData">
                <xs:sequence>
                    <xs:element minOccurs="0" name="addOnStatus" type="tns:subscriptionState"/>
                    <xs:element minOccurs="0" name="addonSubscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="packageDescription" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageId" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageName" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageType" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="quotaProfileBalances" nillable="true" type="tns:quotaProfileBalance"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="usageResetTime" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
            <xs:simpleType name="subscriptionState">
                <xs:restriction base="xs:string">
                    <xs:enumeration value="SUBSCRIBED"/>
                    <xs:enumeration value="START_SCHEDULED"/>
                    <xs:enumeration value="STARTED"/>
                    <xs:enumeration value="EXPIRY_SCHEDULED"/>
                    <xs:enumeration value="EXPIRED"/>
                    <xs:enumeration value="UNSUBSCRIBED"/>
                    <xs:enumeration value="APPROVAL_PENDING"/>
                    <xs:enumeration value="REJECTED"/>
                    <xs:enumeration value="UNPROCESSED"/>
                    <xs:enumeration value="ACTIVE"/>
                    <xs:enumeration value="STOP"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:complexType name="quotaProfileBalance">
                <xs:sequence>
                    <xs:element minOccurs="0" name="allServiceBalance" type="tns:usageInfo"/>
                    <xs:element minOccurs="0" name="quotaProfileId" type="xs:string"/>
                    <xs:element minOccurs="0" name="quotaProfileName" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="usageInfos" nillable="true" type="tns:usageInfo"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="usageInfo">
                <xs:sequence>
                    <xs:element minOccurs="0" name="aggregationKey" type="xs:string"/>
                    <xs:element minOccurs="0" name="balance" type="tns:usage"/>
                    <xs:element minOccurs="0" name="curretUsage" type="tns:usage"/>
                    <xs:element minOccurs="0" name="HSQLimit" type="tns:usage"/>
                    <xs:element minOccurs="0" name="serviceId" type="xs:string"/>
                    <xs:element minOccurs="0" name="serviceName" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="usage">
                <xs:sequence>
                    <xs:element minOccurs="0" name="downloadOctets" type="xs:long"/>
                    <xs:element minOccurs="0" name="time" type="xs:long"/>
                    <xs:element minOccurs="0" name="totalOctets" type="xs:long"/>
                    <xs:element minOccurs="0" name="uploadOctets" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>

        </xs:schema>


    </wsdl:types>

    <wsdl:message name="AuthenticateUser">
        <wsdl:part element="tns:wsAuthenticateUser" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="AuthenticateUserResponse">
        <wsdl:part element="tns:wsAuthenticateUserResponse" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="UpdateUserUsage">
        <wsdl:part element="tns:wsUpdateUserUsage" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="UpdateUserUsageResponse">
        <wsdl:part element="tns:wsUpdateUserUsageResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>

    <wsdl:message name="UserLoginStatus">
        <wsdl:part element="tns:wsUserLoginStatus" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="UserLoginStatusResponse">
        <wsdl:part element="tns:wsUserLoginStatusResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>

    <wsdl:message name="GetUserSessionResponse">
        <wsdl:part element="tns:wsGetUserSessionResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>

    <wsdl:message name="GetUserSession">
        <wsdl:part element="tns:wsGetUserSession" name="parameters">
        </wsdl:part>
    </wsdl:message>

    <wsdl:message name="LogoffUserSessionResponse">
        <wsdl:part element="tns:wsLogoffUserSessionResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>

    <wsdl:message name="LogoffUserSession">
        <wsdl:part element="tns:wsLogoffUserSession" name="parameters">
        </wsdl:part>
    </wsdl:message>

    <wsdl:message name="GetAccountDetails">
        <wsdl:part element="tns:wsGetAccountDetails" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="SessionLoginStatus">
        <wsdl:part element="tns:wsSessionLoginStatus" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="SessionLoginStatusResponse">
        <wsdl:part element="tns:wsSessionLoginStatusResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>

    <wsdl:message name="UpdateAccountResponse">
        <wsdl:part element="tns:wsUpdateAccountResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="UpdateAccount">
        <wsdl:part element="tns:wsUpdateAccount" name="parameters">
        </wsdl:part>
    </wsdl:message>

    <wsdl:message name="ResetUsageForAccount">
        <wsdl:part element="tns:wsResetUsageForAccount" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="ResetUsageForAccountResponse">
        <wsdl:part element="tns:wsResetUsageForAccountResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>

    <wsdl:message name="GetAccountDetailsResponse">
        <wsdl:part element="tns:wsGetAccountDetailsResponse" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="AddAccount">
        <wsdl:part element="tns:wsAddAccount" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="AddAccountResponse">
        <wsdl:part element="tns:wsAddAccountResponse" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="GetUserUsageSummary">
        <wsdl:part element="tns:wsGetUserUsageSummary" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="GetUserUsageSummaryResponse">
        <wsdl:part element="tns:wsGetUserUsageSummaryResponse" name="parameters"></wsdl:part>
    </wsdl:message>


    <wsdl:message name="AddServiceToAccountResponse">
        <wsdl:part element="tns:wsAddServiceToAccountResponse" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="AddServiceToAccount">
        <wsdl:part element="tns:wsAddServiceToAccount" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="ChangeService">
        <wsdl:part element="tns:wsChangeService" name="parameters"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="ChangeServiceResponse">
        <wsdl:part element="tns:wsChangeServiceResponse" name="parameters"> </wsdl:part>
    </wsdl:message>

    <wsdl:message name="GetAccountName">
        <wsdl:part element="tns:wsGetAccountName" name="parameters"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="GetAccountNameResponse">
        <wsdl:part element="tns:wsGetAccountNameResponse" name="parameters"> </wsdl:part>
    </wsdl:message>

    <wsdl:message name="RemoveAccount">
        <wsdl:part element="tns:wsRemoveAccount" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="RemoveAccountResponse">
        <wsdl:part element="tns:wsRemoveAccountResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>

    <wsdl:message name="LoginSessionResponse">
        <wsdl:part element="tns:wsLoginSessionResponse" name="parameters"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="LoginSession">
        <wsdl:part element="tns:wsLoginSession" name="parameters"> </wsdl:part>
    </wsdl:message>

    <wsdl:message name="LogoffUserSessions">
        <wsdl:part element="tns:wsLogoffUserSessions" name="parameters"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="LogoffUserSessionsResponse">
        <wsdl:part element="tns:wsLogoffUserSessionsResponse" name="parameters"> </wsdl:part>
    </wsdl:message>

    <wsdl:message name="GetBalance">
        <wsdl:part element="tns:wsGetBalance" name="parameters"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="BalanceEnquiryResponse">
        <wsdl:part element="tns:wsBalanceEnquiryResponse" name="parameters"> </wsdl:part>
    </wsdl:message>

    <wsdl:portType name="QodSubscriberOperation">

        <wsdl:operation name="LogoffUserSessions">
            <wsdl:input message="tns:LogoffUserSessions" name="LogoffUserSessions"> </wsdl:input>
            <wsdl:output message="tns:LogoffUserSessionsResponse" name="LogoffUserSessionsResponse"> </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetAccountDetails">
            <wsdl:input message="tns:GetAccountDetails" name="GetAccountDetails"></wsdl:input>
            <wsdl:output message="tns:GetAccountDetailsResponse" name="GetAccountDetailsResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="UpdateUserUsage">
            <wsdl:input message="tns:UpdateUserUsage" name="UpdateUserUsage">
            </wsdl:input>
            <wsdl:output message="tns:UpdateUserUsageResponse" name="UpdateUserUsageResponse">
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="UserLoginStatus">
            <wsdl:input message="tns:UserLoginStatus" name="UserLoginStatus">
            </wsdl:input>
            <wsdl:output message="tns:UserLoginStatusResponse" name="UserLoginStatusResponse">
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetUserSession">
            <wsdl:input message="tns:GetUserSession" name="GetUserSession">
            </wsdl:input>
            <wsdl:output message="tns:GetUserSessionResponse" name="GetUserSessionResponse">
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="LogoffUserSession">
            <wsdl:input message="tns:LogoffUserSession" name="LogoffUserSession">
            </wsdl:input>
            <wsdl:output message="tns:LogoffUserSessionResponse" name="LogoffUserSessionResponse">
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="AuthenticateUser">
            <wsdl:input message="tns:AuthenticateUser" name="AuthenticateUser"></wsdl:input>
            <wsdl:output message="tns:AuthenticateUserResponse" name="AuthenticateUserResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="AddAccount">
            <wsdl:input message="tns:AddAccount" name="AddAccount"></wsdl:input>
            <wsdl:output message="tns:AddAccountResponse" name="AddAccountResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetUserUsageSummary">
            <wsdl:input message="tns:GetUserUsageSummary" name="GetUserUsageSummary"></wsdl:input>
            <wsdl:output message="tns:GetUserUsageSummaryResponse" name="GetUserUsageSummaryResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="AddServiceToAccount">
            <wsdl:input message="tns:AddServiceToAccount" name="AddServiceToAccount"></wsdl:input>
            <wsdl:output message="tns:AddServiceToAccountResponse" name="AddServiceToAccountResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="ChangeService">
            <wsdl:input message="tns:ChangeService" name="ChangeService"> </wsdl:input>
            <wsdl:output message="tns:ChangeServiceResponse" name="ChangeServiceResponse"> </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="RemoveAccount">
            <wsdl:input message="tns:RemoveAccount" name="RemoveAccount">
            </wsdl:input>
            <wsdl:output message="tns:RemoveAccountResponse" name="RemoveAccountResponse">
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="ResetUsageForAccount">
            <wsdl:input message="tns:ResetUsageForAccount" name="ResetUsageForAccount">
            </wsdl:input>
            <wsdl:output message="tns:ResetUsageForAccountResponse" name="ResetUsageForAccountResponse">
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="LoginSession">
            <wsdl:input message="tns:LoginSession" name="LoginSession"> </wsdl:input>
            <wsdl:output message="tns:LoginSessionResponse" name="LoginSessionResponse"> </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetAccountName">
            <wsdl:input message="tns:GetAccountName" name="GetAccountName"> </wsdl:input>
            <wsdl:output message="tns:GetAccountNameResponse" name="GetAccountNameResponse"> </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="SessionLoginStatus">
            <wsdl:input message="tns:SessionLoginStatus" name="SessionLoginStatus">
            </wsdl:input>
            <wsdl:output message="tns:SessionLoginStatusResponse" name="SessionLoginStatusResponse">
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="UpdateAccount">
            <wsdl:input message="tns:UpdateAccount" name="UpdateAccount">
            </wsdl:input>
            <wsdl:output message="tns:UpdateAccountResponse" name="UpdateAccountResponse">
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetBalance">
            <wsdl:input message="tns:GetBalance" name="GetBalance"> </wsdl:input>
            <wsdl:output message="tns:BalanceEnquiryResponse" name="BalanceEnquiryResponse"> </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>