<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://api.act.com/"
                  xmlns:sch="http://subscription.ws.nvsmx.elitecore.com/"
                  xmlns:rch="http://sessionmanagement.ws.nvsmx.elitecore.com/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  targetNamespace="http://api.act.com/">

    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
                   targetNamespace="http://api.act.com/">

            <xs:element name="wsAuthenticateUser">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="actionItem" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="requestId" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="userName" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="password" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsGetAccountDetails">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="actionItem" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="requestId" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="userName" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>


            <!--            <xs:element name="wsGetBalance">-->
            <!--                <xs:complexType>-->
            <!--                    <xs:sequence>-->
            <!--                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="alternateId" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="packageId" type="xs:long" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="packageName" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="subscriptionId" type="xs:long" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="parameter1" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="parameter2" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                    </xs:sequence>-->
            <!--                </xs:complexType>-->
            <!--            </xs:element>-->

            <xs:element name="wsChangeService">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="userName" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="overrides" type="xs:double" minOccurs="0" form="unqualified"/>
                        <xs:element name="serviceId" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsGetAccountName">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="ipAddress" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsLoginSession">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="ipAddress" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="userName" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="password" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsLogoffUserSessions">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="userName" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsRemoveAccount">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="userName" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsResetUsageForAccount">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="userName" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsSessionLoginStatus">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="ipAddress" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsUserLoginStatus">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="userName" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsGetUserSession">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="ipAddress" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsAddAccount">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="userName" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="password" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="serviceId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="item" minOccurs="0" maxOccurs="unbounded" form="unqualified">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="key" type="xs:string" minOccurs="0" form="unqualified"/>
                                    <xs:element name="value" type="xs:string" minOccurs="0" form="unqualified"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsUpdateAccount">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="userName" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="item" minOccurs="0" maxOccurs="unbounded" form="unqualified">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="key" type="xs:string" minOccurs="0" form="unqualified"/>
                                    <xs:element name="value" type="xs:string" minOccurs="0" form="unqualified"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsGetUserUsageSummary">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsUpdateUserUsage">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="userName" type="xs:string" form="unqualified"/>
                        <xs:element name="usageBytes" type="xs:double" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsLogoffUserSession">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="ipAddress" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsAddServiceToAccount">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actionItem" type="xs:string" form="unqualified"/>
                        <xs:element name="requestId" type="xs:string" form="unqualified"/>
                        <xs:element name="userName" type="xs:string" form="unqualified"/>
                        <xs:element name="serviceId" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

        </xs:schema>

    </wsdl:types>

    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   elementFormDefault="unqualified"
                   targetNamespace="http://api.act.com/">

            <!--            <xs:element name="wsAuthenticateUser" type="tns:wsAuthenticateUser"/>-->
            <xs:element name="wsAuthenticateUserResponse" type="tns:wsAuthenticateUserResponse"/>
            <!--            <xs:element name="wsGetAccountDetails" type="tns:wsGetAccountDetails"/>-->
            <xs:element name="wsGetAccountDetailsResponse" type="tns:wsGetAccountDetailsResponse"/>
            <xs:element name="wsUpdateAccountResponse" type="tns:wsUpdateAccountResponse"/>

            <xs:complexType name="wsUpdateAccountResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="UpdateAccount" type="tns:updateAccountResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="updateAccountResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <!--            <xs:complexType name="wsAuthenticateUser">-->
            <!--                <xs:sequence>-->
            <!--                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>-->
            <!--                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>-->
            <!--                    <xs:element minOccurs="0" name="userName" type="xs:string"/>-->
            <!--                    <xs:element minOccurs="0" name="password" type="xs:string"/>-->
            <!--                </xs:sequence>-->
            <!--            </xs:complexType>-->
            <xs:complexType name="wsAuthenticateUserResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="AuthenticateUser" type="tns:authenticateUserResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="authenticateUserResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element name="result" type="xs:boolean"/>
                </xs:sequence>
            </xs:complexType>

            <!--            <xs:complexType name="wsGetAccountDetails">-->
            <!--                <xs:sequence>-->
            <!--                    <xs:element minOccurs="0" name="actionItem" type="xs:string"/>-->
            <!--                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>-->
            <!--                    <xs:element minOccurs="0" name="userName" type="xs:string"/>-->
            <!--                </xs:sequence>-->
            <!--            </xs:complexType>-->
            <xs:complexType name="wsGetAccountDetailsResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="GetAccountDetails" type="tns:getAccountDetailsResponse"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="getAccountDetailsResponse">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="item" nillable="true"
                                type="tns:subscriberMapEntry"/>
                    <xs:element minOccurs="0" name="password" type="xs:string"/>
                    <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                    <xs:element name="responeCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element minOccurs="0" name="serviceId" type="xs:string"/>
                    <xs:element minOccurs="0" name="userName" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>


            <xs:complexType name="subscriberMapEntry">
                <xs:sequence>
                    <xs:element minOccurs="0" name="key" type="xs:string"/>
                    <xs:element minOccurs="0" name="value" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

        </xs:schema>

    </wsdl:types>


    <!-- Second Service: wsChangeTopUpSubscription -->
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   elementFormDefault="qualified"
                   targetNamespace="http://subscription.ws.nvsmx.elitecore.com/"
                   xmlns:sub="http://subscription.ws.nvsmx.elitecore.com/">
            <xs:element name="wsListAddOnSubscriptions" type="sub:wsListAddOnSubscriptions"/>
            <xs:element name="wsListTopUpSubscriptions">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="subscriberId" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="alternateId" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="subscriptionStatusValue" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="subscriptionStatusName" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="parameter1" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="parameter2" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:complexType name="wsListAddOnSubscriptions">
                <xs:sequence>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusValue" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusName" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

            <!--            <xs:element name="wsChangeTopUpSubscription">-->
            <!--                <xs:complexType>-->
            <!--                    <xs:sequence>-->
            <!--                        <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="updateAction" type="xs:int" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="topUpSubscriptionId" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="subscriptionStatusValue" type="xs:int" minOccurs="0" form="unqualified"/>-->
            <!--                    </xs:sequence>-->
            <!--                </xs:complexType>-->
            <!--            </xs:element>-->

            <!--            <xs:element name="wsSubscribeTopUp">-->
            <!--                <xs:complexType>-->
            <!--                    <xs:sequence>-->
            <!--                        <xs:element name="subscriberId" type="xs:string" form="unqualified"/>-->
            <!--                        <xs:element name="updateAction" type="xs:int" form="unqualified"/>-->
            <!--                        <xs:element name="topUpPackageName" type="xs:string" form="unqualified"/>-->
            <!--                        <xs:element name="subscriptionStatusValue" type="xs:int" form="unqualified"/>-->
            <!--                        <xs:element name="startTime" type="xs:long" form="unqualified"/>-->
            <!--                        <xs:element name="endTime" type="xs:long" form="unqualified"/>-->
            <!--                    </xs:sequence>-->
            <!--                </xs:complexType>-->
            <!--            </xs:element>-->

            <!--            <xs:element name="wsChangeAddOnSubscription">-->
            <!--                <xs:complexType>-->
            <!--                    <xs:sequence>-->
            <!--                        <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified" />-->
            <!--                        <xs:element name="alternateId" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="updateAction" type="xs:int" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="addOnSubscriptionId" type="xs:int" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="subscriptionStatusValue" type="xs:int" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="subscriptionStatusName" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="addOnName" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="subscriptionOrder" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="startTime" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="endTime" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="rejectReason" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="parameter1" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="parameter2" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                    </xs:sequence>-->
            <!--                </xs:complexType>-->
            <!--            </xs:element>-->

            <!--            <xs:element name="wsGetBalance">-->
            <!--                <xs:complexType>-->
            <!--                    <xs:sequence>-->
            <!--                        <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                    </xs:sequence>-->
            <!--                </xs:complexType>-->
            <!--            </xs:element>-->

            <!--            <xs:element name="wsSubscribeAddOn">-->
            <!--                <xs:complexType>-->
            <!--                    <xs:sequence>-->
            <!--                        <xs:element name="parentId" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="alternateId" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="updateAction" type="xs:int" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="cui" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="addOnPackageId" type="xs:int" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="addOnPackageName" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="subscriptionStatusValue" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="subscriptionStatusName" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="startTime" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="endTime" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="parameter1" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                        <xs:element name="parameter2" type="xs:string" minOccurs="0" form="unqualified"/>-->
            <!--                    </xs:sequence>-->
            <!--                </xs:complexType>-->
            <!--            </xs:element>-->


        </xs:schema>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://subscription.ws.nvsmx.elitecore.com/"
                   elementFormDefault="unqualified" targetNamespace="http://subscription.ws.nvsmx.elitecore.com/"
                   version="1.0">

            <xs:element name="wsGetBalance" type="tns:wsGetBalance"/>
            <xs:element name="wsGetBalanceResponse" type="tns:wsGetBalanceResponse"/>
            <xs:element name="wsListAddOnSubscriptions" type="tns:wsListAddOnSubscriptions"/>
            <xs:element name="wsListAddOnSubscriptionsResponse" type="tns:wsListAddOnSubscriptionsResponse"/>
            <xs:element name="wsSubscribeAddOn" type="tns:wsSubscribeAddOn"/>
            <xs:element name="wsSubscribeAddOnResponse" type="tns:wsSubscribeAddOnResponse"/>
            <xs:element name="wsSubscribeTopUp" type="tns:wsSubscribeTopUp"/>
            <xs:element name="wsSubscribeTopUpResponse" type="tns:wsSubscribeTopUpResponse"/>
            <xs:element name="wsChangeAddOnSubscription" type="tns:wsChangeAddOnSubscription"/>
            <xs:element name="wsChangeAddOnSubscriptionResponse" type="tns:wsChangeAddOnSubscriptionResponse"/>
            <xs:element name="wsChangeTopUpSubscription" type="tns:wsChangeTopUpSubscription"/>
            <xs:element name="wsChangeTopUpSubscriptionResponse" type="tns:wsChangeTopUpSubscriptionResponse"/>


            <xs:complexType name="wsChangeTopUpSubscription">
                <xs:sequence>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="updateAction" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpSubscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusValue" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusName" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpName" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionOrder" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="rejectReason" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsChangeTopUpSubscriptionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="tns:topUpSubscriptionResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="topUpSubscriptionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="topUpSubscriptions" nillable="true"
                                type="tns:topUpSubscriptionData"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsChangeAddOnSubscription">
                <xs:sequence>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="updateAction" type="xs:string"/>
                    <xs:element minOccurs="0" name="addOnSubscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusValue" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusName" type="xs:string"/>
                    <xs:element minOccurs="0" name="addOnName" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionOrder" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="rejectReason" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsChangeAddOnSubscriptionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="tns:subscriptionResponse"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="wsSubscribeTopUp">
                <xs:sequence>
                    <xs:element minOccurs="0" name="parentId" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="updateAction" type="xs:string"/>
                    <xs:element minOccurs="0" name="cui" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpPackageId" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpPackageName" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusValue" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusName" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsSubscribeTopUpResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="tns:topUpSubscriptionResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="topUpSubscriptionResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="topUpSubscriptions" nillable="true"
                                type="tns:topUpSubscriptionData"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="topUpSubscriptionData">
                <xs:sequence>
                    <xs:element minOccurs="0" name="endTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="subscriberIdentity" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpId" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpName" type="xs:string"/>
                    <xs:element minOccurs="0" name="topUpStatus" type="tns:subscriptionState"/>
                    <xs:element minOccurs="0" name="topUpSubscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="usageResetTime" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>


            <xs:complexType name="wsSubscribeAddOn">
                <xs:sequence>
                    <xs:element minOccurs="0" name="parentId" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="updateAction" type="xs:string"/>
                    <xs:element minOccurs="0" name="cui" type="xs:string"/>
                    <xs:element minOccurs="0" name="addOnPackageId" type="xs:string"/>
                    <xs:element minOccurs="0" name="addOnPackageName" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusValue" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusName" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsSubscribeAddOnResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="tns:subscriptionResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:simpleType name="subscriptionState">
                <xs:restriction base="xs:string">
                    <xs:enumeration value="SUBSCRIBED"/>
                    <xs:enumeration value="START_SCHEDULED"/>
                    <xs:enumeration value="STARTED"/>
                    <xs:enumeration value="EXPIRY_SCHEDULED"/>
                    <xs:enumeration value="EXPIRED"/>
                    <xs:enumeration value="UNSUBSCRIBED"/>
                    <xs:enumeration value="APPROVAL_PENDING"/>
                    <xs:enumeration value="REJECTED"/>
                    <xs:enumeration value="UNPROCESSED"/>
                    <xs:enumeration value="ACTIVE"/>
                    <xs:enumeration value="STOP"/>
                </xs:restriction>
            </xs:simpleType>

            <xs:complexType name="wsGetBalance">
                <xs:sequence>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageId" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageName" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsGetBalanceResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="tns:balanceEnquiryResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="balanceEnquiryResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="subscriptionInformations" nillable="true"
                                type="tns:subscriptionInformationData"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="subscriptionInformationData">
                <xs:sequence>
                    <xs:element minOccurs="0" name="addOnStatus" type="tns:subscriptionState"/>
                    <xs:element minOccurs="0" name="addonSubscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="packageDescription" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageId" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageName" type="xs:string"/>
                    <xs:element minOccurs="0" name="packageType" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="quotaProfileBalances" nillable="true"
                                type="tns:quotaProfileBalance"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="usageResetTime" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="quotaProfileBalance">
                <xs:sequence>
                    <xs:element minOccurs="0" name="allServiceBalance" type="tns:usageInfo"/>
                    <xs:element minOccurs="0" name="quotaProfileId" type="xs:string"/>
                    <xs:element minOccurs="0" name="quotaProfileName" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="usageInfos" nillable="true"
                                type="tns:usageInfo"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="usageInfo">
                <xs:sequence>
                    <xs:element minOccurs="0" name="aggregationKey" type="xs:string"/>
                    <xs:element minOccurs="0" name="balance" type="tns:usage"/>
                    <xs:element minOccurs="0" name="curretUsage" type="tns:usage"/>
                    <xs:element minOccurs="0" name="HSQLimit" type="tns:usage"/>
                    <xs:element minOccurs="0" name="serviceId" type="xs:string"/>
                    <xs:element minOccurs="0" name="serviceName" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="usage">
                <xs:sequence>
                    <xs:element minOccurs="0" name="downloadOctets" type="xs:long"/>
                    <xs:element minOccurs="0" name="time" type="xs:long"/>
                    <xs:element minOccurs="0" name="totalOctets" type="xs:long"/>
                    <xs:element minOccurs="0" name="uploadOctets" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsListAddOnSubscriptions">
                <xs:sequence>
                    <xs:element minOccurs="0" name="subscriberId" type="xs:string"/>
                    <xs:element minOccurs="0" name="alternateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusValue" type="xs:string"/>
                    <xs:element minOccurs="0" name="subscriptionStatusName" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="wsListAddOnSubscriptionsResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="tns:subscriptionResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="subscriptionResponse">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="addOnSubscriptions" nillable="true"
                                type="tns:subscriptionData"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="subscriptionData">
                <xs:sequence>
                    <xs:element minOccurs="0" name="addOnId" type="xs:string"/>
                    <xs:element minOccurs="0" name="addOnName" type="xs:string"/>
                    <xs:element minOccurs="0" name="addOnStatus" type="tns:subscriptionState"/>
                    <xs:element minOccurs="0" name="addonSubscriptionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="endTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="parameter1" type="xs:string"/>
                    <xs:element minOccurs="0" name="parameter2" type="xs:string"/>
                    <xs:element minOccurs="0" name="startTime" type="xs:long"/>
                    <xs:element minOccurs="0" name="subscriberIdentity" type="xs:string"/>
                    <xs:element minOccurs="0" name="usageResetTime" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>

        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   xmlns:tns="http://sessionmanagement.ws.nvsmx.elitecore.com/"
                   elementFormDefault="unqualified"
                   targetNamespace="http://sessionmanagement.ws.nvsmx.elitecore.com/"
                   version="1.0">

            <xs:element name="wsReauthSessionsBySubscriberIdentity">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="subscriberId" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="alternateId" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="parameter1" type="xs:string" form="unqualified"/>
                        <xs:element minOccurs="0" name="parameter2" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="wsReauthSessionsBySubscriberIdentityResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="return" type="tns:sessionReAuthResponse"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:complexType name="sessionReAuthResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="responseCode" type="xs:int"/>
                    <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>

    </wsdl:types>

    <wsdl:types>
        <!--        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"-->
        <!--                   xmlns:ses="http://sessionmanagement.ws.nvsmx.elitecore.com/"-->
        <!--                   targetNamespace="http://sessionmanagement.ws.nvsmx.elitecore.com/"-->
        <!--                   elementFormDefault="qualified">-->

        <!--            <xs:element name="wsReauthSessionsBySubscriberIdentity">-->
        <!--                <xs:complexType>-->
        <!--                    <xs:sequence>-->
        <!--                        <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified"/>-->
        <!--                        <xs:element name="alternateId" type="xs:string" minOccurs="0" form="unqualified"/>-->
        <!--                        <xs:element name="parameter1" type="xs:string" minOccurs="0" form="unqualified"/>-->
        <!--                        <xs:element name="parameter2" type="xs:string" minOccurs="0" form="unqualified"/>-->
        <!--                    </xs:sequence>-->
        <!--                </xs:complexType>-->
        <!--            </xs:element>-->
        <!--        </xs:schema>-->
    </wsdl:types>


    <wsdl:message name="AuthenticateUser">
        <wsdl:part element="tns:wsAuthenticateUser" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="AuthenticateUserResponse">
        <wsdl:part element="tns:wsAuthenticateUserResponse" name="parameters"></wsdl:part>
    </wsdl:message>


    <wsdl:message name="GetAccountDetails">
        <wsdl:part element="tns:wsGetAccountDetails" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="GetAccountDetailsResponse">
        <wsdl:part element="tns:wsGetAccountDetailsResponse" name="parameters"></wsdl:part>
    </wsdl:message>


    <wsdl:message name="UpdateAccountResponse">
        <wsdl:part element="tns:wsUpdateAccountResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="UpdateAccount">
        <wsdl:part element="tns:wsUpdateAccount" name="parameters">
        </wsdl:part>
    </wsdl:message>


    <wsdl:message name="wsSubscribeTopUpResponse">
        <wsdl:part element="sch:wsSubscribeTopUpResponse" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsSubscribeTopUp">
        <wsdl:part element="sch:wsSubscribeTopUp" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="wsSubscribeAddOn">
        <wsdl:part element="sch:wsSubscribeAddOn" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsSubscribeAddOnResponse">
        <wsdl:part element="sch:wsSubscribeAddOnResponse" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="wsChangeTopUpSubscription">
        <wsdl:part element="sch:wsChangeTopUpSubscription" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsChangeTopUpSubscriptionResponse">
        <wsdl:part element="sch:wsChangeTopUpSubscriptionResponse" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="wsReauthSessionsBySubscriberIdentity">
        <wsdl:part element="rch:wsReauthSessionsBySubscriberIdentity" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsReauthSessionsBySubscriberIdentityResponse">
        <wsdl:part element="rch:wsReauthSessionsBySubscriberIdentityResponse" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="wsGetBalance">
        <wsdl:part element="sch:wsGetBalance" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsGetBalanceResponse">
        <wsdl:part element="sch:wsGetBalanceResponse" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="wsListAddOnSubscriptions">
        <wsdl:part element="sch:wsListAddOnSubscriptions" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsListAddOnSubscriptionsResponse">
        <wsdl:part element="sch:wsListAddOnSubscriptionsResponse" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="wsChangeAddOnSubscription">
        <wsdl:part element="sch:wsChangeAddOnSubscription" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="wsChangeAddOnSubscriptionResponse">
        <wsdl:part element="sch:wsChangeAddOnSubscriptionResponse" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:portType name="QodSubscriberOperation">

        <wsdl:operation name="AuthenticateUser">
            <wsdl:input message="tns:AuthenticateUser" name="AuthenticateUser"></wsdl:input>
            <wsdl:output message="tns:AuthenticateUserResponse" name="AuthenticateUserResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetAccountDetails">
            <wsdl:input message="tns:GetAccountDetails" name="GetAccountDetails"></wsdl:input>
            <wsdl:output message="tns:GetAccountDetailsResponse" name="GetAccountDetailsResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="UpdateAccount">
            <wsdl:input message="tns:UpdateAccount" name="UpdateAccount">
            </wsdl:input>
            <wsdl:output message="tns:UpdateAccountResponse" name="UpdateAccountResponse">
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsSubscribeTopUp">
            <wsdl:input message="tns:wsSubscribeTopUp" name="wsSubscribeTopUp"></wsdl:input>
            <wsdl:output message="tns:wsSubscribeTopUpResponse" name="wsSubscribeTopUpResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsSubscribeAddOn">
            <wsdl:input message="tns:wsSubscribeAddOn" name="wsSubscribeAddOn"></wsdl:input>
            <wsdl:output message="tns:wsSubscribeAddOnResponse" name="wsSubscribeAddOnResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsChangeTopUpSubscription">
            <wsdl:input message="tns:wsChangeTopUpSubscription" name="wsChangeTopUpSubscription"></wsdl:input>
            <wsdl:output message="tns:wsChangeTopUpSubscriptionResponse"
                         name="wsChangeTopUpSubscriptionResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsGetBalance">
            <wsdl:input message="tns:wsGetBalance" name="wsGetBalance"></wsdl:input>
            <wsdl:output message="tns:wsGetBalanceResponse" name="wsGetBalanceResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsReauthSessionsBySubscriberIdentity">
            <wsdl:input message="tns:wsReauthSessionsBySubscriberIdentity"
                        name="wsReauthSessionsBySubscriberIdentity"></wsdl:input>
            <wsdl:output message="tns:wsReauthSessionsBySubscriberIdentityResponse"
                         name="wsReauthSessionsBySubscriberIdentityResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsListAddOnSubscriptions">
            <wsdl:input message="tns:wsListAddOnSubscriptions" name="wsListAddOnSubscriptions"></wsdl:input>
            <wsdl:output message="tns:wsListAddOnSubscriptionsResponse"
                         name="wsListAddOnSubscriptionsResponse"></wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsChangeAddOnSubscription">
            <wsdl:input message="tns:wsChangeAddOnSubscription" name="wsChangeAddOnSubscription"></wsdl:input>
            <wsdl:output message="tns:wsChangeAddOnSubscriptionResponse"
                         name="wsChangeAddOnSubscriptionResponse"></wsdl:output>
        </wsdl:operation>

    </wsdl:portType>

    <wsdl:binding name="SubscriptionServiceSoapBinding" type="tns:QodSubscriberOperation">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="wsSubscribeAddOn">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsSubscribeAddOn">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsSubscribeAddOnResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsChangeTopUpSubscription">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsChangeTopUpSubscription">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsChangeTopUpSubscriptionResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>


        <wsdl:operation name="wsSubscribeTopUp">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsSubscribeTopUp">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsSubscribeTopUpResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsGetBalance">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsGetBalance">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsGetBalanceResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsListAddOnSubscriptions">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsListAddOnSubscriptions">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsListAddOnSubscriptionsResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsReauthSessionsBySubscriberIdentity">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsReauthSessionsBySubscriberIdentity">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsReauthSessionsBySubscriberIdentityResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsChangeAddOnSubscription">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsChangeAddOnSubscription">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsChangeAddOnSubscriptionResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>


    </wsdl:binding>

    <wsdl:binding name="QodOperationsSoapBinding" type="tns:QodSubscriberOperation">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="GetAccountDetails">
            <soap:operation soapAction="http://elitecore.com/soap/GetAccountDetails" style="document"/>
            <wsdl:input name="GetAccountDetails">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="GetAccountDetailsResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="AuthenticateUser">
            <soap:operation soapAction="http://elitecore.com/soap/AuthenticateUser" style="document"/>
            <wsdl:input name="AuthenticateUser">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="AuthenticateUserResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="UpdateAccount">
            <soap:operation soapAction="http://elitecore.com/soap/UpdateAccount" style="document"/>
            <wsdl:input name="UpdateAccount">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="UpdateAccountResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

    </wsdl:binding>


    <wsdl:message name="wsAuthenticateUser">
        <wsdl:part element="tns:wsAuthenticateUser" name="wsAuthenticateUser"/>
    </wsdl:message>

    <wsdl:portType name="WsAuthenticateUserPort">
        <wsdl:operation name="wsAuthenticateUser">
            <wsdl:input message="tns:wsAuthenticateUser" name="wsAuthenticateUser"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="QodWsAuthenticateUserBinding" type="tns:WsAuthenticateUserPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsAuthenticateUser">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsAuthenticateUser">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="WsAuthenticateUserPortService">
        <wsdl:port binding="tns:QodWsAuthenticateUserBinding" name="AuthenticatePort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="wsGetAccountDetails">
        <wsdl:part element="tns:wsGetAccountDetails" name="wsGetAccountDetails"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="WsGetAccountDetailsPort">
        <wsdl:operation name="wsGetAccountDetails">
            <wsdl:input message="tns:wsGetAccountDetails" name="wsGetAccountDetails"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QodWsGetAccountDetailsBinding" type="tns:WsGetAccountDetailsPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsGetAccountDetails">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsGetAccountDetails">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WsGetAccountDetailsPortService">
        <wsdl:port binding="tns:QodWsGetAccountDetailsBinding" name="GetAccountDetailsPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <!--    <wsdl:message name="wsReauthSessionsBySubscriberIdentityRequest">-->
    <!--        <wsdl:part element="rch:wsReauthSessionsBySubscriberIdentity" name="wsReauthSessionsBySubscriberIdentity"/>-->
    <!--    </wsdl:message>-->
    <!--    &lt;!&ndash; Define PortTypes &ndash;&gt;-->
    <!--    <wsdl:portType name="wsReauthSessionsBySubscriberIdentityPort">-->
    <!--        <wsdl:operation name="wsReauthSessionsBySubscriberIdentity">-->
    <!--            <wsdl:input message="rch:wsReauthSessionsBySubscriberIdentityRequest"/>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:portType>-->
    <!--    &lt;!&ndash; Define Bindings &ndash;&gt;-->
    <!--    <wsdl:binding name="QodReauthSessionsBySubscriberIdentityBinding" type="rch:wsReauthSessionsBySubscriberIdentityPort">-->
    <!--        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>-->
    <!--        <wsdl:operation name="wsReauthSessionsBySubscriberIdentity">-->
    <!--            <soap:operation soapAction="http://sessionmanagement.ws.nvsmx.elitecore.com/wsReauthSessionsBySubscriberIdentity"/>-->
    <!--            <wsdl:input>-->
    <!--                <soap:body use="literal" namespace="http://sessionmanagement.ws.nvsmx.elitecore.com"/>-->
    <!--            </wsdl:input>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:binding>-->
    <!--    <wsdl:service name="wsReauthSessionsBySubscriberIdentityService">-->
    <!--        <wsdl:port binding="rch:QodReauthSessionsBySubscriberIdentityBinding" name="wsReauthSessionsBySubscriberIdentityPort">-->
    <!--            <soap:address location="http://localhost:41080/new-api/QodServices"/>-->
    <!--        </wsdl:port>-->
    <!--    </wsdl:service>-->

    <wsdl:service name="QodOperations">
        <wsdl:port binding="tns:QodOperationsSoapBinding" name="QodOperationsService">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>









    <!--    <wsdl:message name="wsChangeTopUpSubscription">-->
    <!--        <wsdl:part element="sch:wsChangeTopUpSubscription" name="wsChangeTopUpSubscription"/>-->
    <!--    </wsdl:message>-->

    <!--    <wsdl:portType name="WsChangeTopUpSubscriptionPort">-->
    <!--        &lt;!&ndash; Ensure the operation references the correct message &ndash;&gt;-->
    <!--        <wsdl:operation name="wsChangeTopUpSubscription">-->
    <!--            <wsdl:input message="sch:wsChangeTopUpSubscription" name="wsChangeTopUpSubscription"/>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:portType>-->

    <!--    &lt;!&ndash; Binding for wsChangeTopUpSubscription &ndash;&gt;-->
    <!--    <wsdl:binding name="QodChangeTopUpSubscriptionBinding" type="sch:WsChangeTopUpSubscriptionPort">-->
    <!--        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>-->
    <!--        <wsdl:operation name="wsChangeTopUpSubscription">-->
    <!--            <soap:operation soapAction=""/>-->
    <!--            <wsdl:input name="wsChangeTopUpSubscription">-->
    <!--                <soap:body use="literal"/>-->
    <!--            </wsdl:input>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:binding>-->

    <!--    &lt;!&ndash; Port and Service for wsChangeTopUpSubscription &ndash;&gt;-->
    <!--    <wsdl:service name="WsChangeTopUpSubscriptionPortService">-->
    <!--        <wsdl:port binding="sch:QodChangeTopUpSubscriptionBinding" name="ChangeTopUpPort">-->
    <!--            <soap:address location="http://localhost:41080/new-api/QodServices"/>-->
    <!--        </wsdl:port>-->
    <!--    </wsdl:service>-->



    <!-- Message for wsChangeTopUpSubscription -->
    <wsdl:message name="wsListAddOnSubscriptions">
        <wsdl:part element="sch:wsListAddOnSubscriptions" name="wsListAddOnSubscriptions"/>
    </wsdl:message>

    <wsdl:portType name="WsListAddOnSubscriptionsPort">
        <!-- Ensure the operation references the correct message -->
        <wsdl:operation name="wsListAddOnSubscriptions">
            <wsdl:input message="sch:wsListAddOnSubscriptions" name="wsListAddOnSubscriptions"/>
        </wsdl:operation>
    </wsdl:portType>

    <!-- Binding for wsChangeTopUpSubscription -->
    <wsdl:binding name="QodListAddOnSubscriptionsBinding" type="sch:WsListAddOnSubscriptionsPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsListAddOnSubscriptions">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsListAddOnSubscriptions">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>

    <!-- Port and Service for wsChangeTopUpSubscription -->
    <wsdl:service name="WsListAddOnSubscriptionsPortService">
        <wsdl:port binding="sch:QodListAddOnSubscriptionsBinding" name="ListAddOnSubscriptions">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>



    <!-- Message for wsChangeTopUpSubscription -->
    <wsdl:message name="wsListTopUpSubscriptions">
        <wsdl:part element="sch:wsListTopUpSubscriptions" name="wsListTopUpSubscriptions"/>
    </wsdl:message>

    <wsdl:portType name="WsListTopUpSubscriptionsPort">
        <!-- Ensure the operation references the correct message -->
        <wsdl:operation name="wsListTopUpSubscriptions">
            <wsdl:input message="sch:wsListTopUpSubscriptions" name="wsListTopUpSubscriptions"/>
        </wsdl:operation>
    </wsdl:portType>

    <!-- Binding for wsChangeTopUpSubscription -->
    <wsdl:binding name="QodListTopUpSubscriptionsBinding" type="sch:WsListTopUpSubscriptionsPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsListTopUpSubscriptions">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsListTopUpSubscriptions">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>

    <!-- Port and Service for wsChangeTopUpSubscription -->
    <wsdl:service name="WsListTopUpSubscriptionsPortService">
        <wsdl:port binding="sch:QodListTopUpSubscriptionsBinding" name="ListTopUpSubscriptions">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>




    <!-- Message for wsSubscribeTopUp -->
    <!--    <wsdl:message name="wsSubscribeTopUp">-->
    <!--        <wsdl:part element="sch:wsSubscribeTopUp" name="wsSubscribeTopUp"/>-->
    <!--    </wsdl:message>-->

    <!--    <wsdl:portType name="wsSubscribeTopUpPort">-->
    <!--        &lt;!&ndash; Ensure the operation references the correct message &ndash;&gt;-->
    <!--        <wsdl:operation name="wsSubscribeTopUp">-->
    <!--            <wsdl:input message="sch:wsSubscribeTopUp" name="wsSubscribeTopUp"/>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:portType>-->

    <!--    &lt;!&ndash; Binding for wsSubscribeTopUp &ndash;&gt;-->
    <!--    <wsdl:binding name="QodSubscribeTopUpBinding" type="sch:wsSubscribeTopUpPort">-->
    <!--        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>-->
    <!--        <wsdl:operation name="wsSubscribeTopUp">-->
    <!--            <soap:operation soapAction="http://subscription.ws.nvsmx.elitecore.com"/>-->
    <!--            <wsdl:input name="wsSubscribeTopUp">-->
    <!--                <soap:body use="literal"/>-->
    <!--            </wsdl:input>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:binding>-->

    <!--    &lt;!&ndash; Port and Service for wsSubscribeTopUp &ndash;&gt;-->
    <!--    <wsdl:service name="wsSubscribeTopUpPortService">-->
    <!--        <wsdl:port binding="sch:QodSubscribeTopUpBinding" name="SubscribeTopUpPort">-->
    <!--            <soap:address location="http://localhost:41080/new-api/QodServices"/>-->
    <!--        </wsdl:port>-->
    <!--    </wsdl:service>-->


    <wsdl:message name="wsChangeService">
        <wsdl:part element="tns:wsChangeService" name="wsChangeService"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="WsChangeServicePort">
        <wsdl:operation name="wsChangeService">
            <wsdl:input message="tns:wsChangeService" name="wsChangeService"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QodChangeServiceBinding" type="tns:WsChangeServicePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsChangeService">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsChangeService">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WsChangeServicePortService">
        <wsdl:port binding="tns:QodChangeServiceBinding" name="ChangeServicePort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <!--    <wsdl:message name="wsGetBalance">-->
    <!--        <wsdl:part element="tns:wsGetBalance" name="wsGetBalance"> </wsdl:part>-->
    <!--    </wsdl:message>-->
    <!--    <wsdl:portType name="WsGetBalancePort">-->
    <!--        <wsdl:operation name="wsGetBalance">-->
    <!--            <wsdl:input message="tns:wsGetBalance" name="wsGetBalance"> </wsdl:input>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:portType>-->
    <!--    <wsdl:binding name="QodGetBalanceBinding" type="tns:WsGetBalancePort">-->
    <!--        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>-->
    <!--        <wsdl:operation name="wsGetBalance">-->
    <!--            <soap:operation soapAction=""/>-->
    <!--            <wsdl:input name="wsGetBalance">-->
    <!--                <soap:body use="literal"/>-->
    <!--            </wsdl:input>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:binding>-->
    <!--    <wsdl:service name="WsGetBalancePortService">-->
    <!--        <wsdl:port binding="tns:QodGetBalanceBinding" name="GetBalancePort">-->
    <!--            <soap:address location="http://localhost:41080/new-api/QodServices"/>-->
    <!--        </wsdl:port>-->
    <!--    </wsdl:service>-->


    <wsdl:message name="wsGetAccountName">
        <wsdl:part element="tns:wsGetAccountName" name="wsGetAccountName"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="WsGetAccountNamePort">
        <wsdl:operation name="wsGetAccountName">
            <wsdl:input message="tns:wsGetAccountName" name="wsGetAccountName"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QodGetAccountNameBinding" type="tns:WsGetAccountNamePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsGetAccountName">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsGetAccountName">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WsGetAccountNamePortService">
        <wsdl:port binding="tns:QodGetAccountNameBinding" name="GetAccountNamePort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="wsLoginSession">
        <wsdl:part element="tns:wsLoginSession" name="wsLoginSession"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="WsLoginSessionPort">
        <wsdl:operation name="wsLoginSession">
            <wsdl:input message="tns:wsLoginSession" name="wsLoginSession"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QodLoginSessionBinding" type="tns:WsLoginSessionPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsLoginSession">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsLoginSession">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WsLoginSessionPortService">
        <wsdl:port binding="tns:QodLoginSessionBinding" name="LoginSessionPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="wsLogoffUserSessions">
        <wsdl:part element="tns:wsLogoffUserSessions" name="wsLogoffUserSessions"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="WsLogoffUserSessionsPort">
        <wsdl:operation name="wsLogoffUserSessions">
            <wsdl:input message="tns:wsLogoffUserSessions" name="wsLogoffUserSessions"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QodLogoffUserSessionsBinding" type="tns:WsLogoffUserSessionsPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsLogoffUserSessions">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsLogoffUserSessions">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WsLogoffUserSessionsPortService">
        <wsdl:port binding="tns:QodLogoffUserSessionsBinding" name="LogoffUserSessionsPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="wsSessionLoginStatus">
        <wsdl:part element="tns:wsSessionLoginStatus" name="wsSessionLoginStatus"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="WsSessionLoginStatusPort">
        <wsdl:operation name="wsSessionLoginStatus">
            <wsdl:input message="tns:wsSessionLoginStatus" name="wsSessionLoginStatus"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QodSessionLoginStatusBinding" type="tns:WsSessionLoginStatusPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsSessionLoginStatus">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsSessionLoginStatus">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WsSessionLoginStatusPortService">
        <wsdl:port binding="tns:QodSessionLoginStatusBinding" name="SessionLoginStatusPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="wsUserLoginStatus">
        <wsdl:part element="tns:wsUserLoginStatus" name="wsUserLoginStatus"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="WsUserLoginStatusPort">
        <wsdl:operation name="wsUserLoginStatus">
            <wsdl:input message="tns:wsUserLoginStatus" name="wsUserLoginStatus"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QodUserLoginStatusBinding" type="tns:WsUserLoginStatusPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsUserLoginStatus">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsUserLoginStatus">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WsUserLoginStatusPortService">
        <wsdl:port binding="tns:QodUserLoginStatusBinding" name="UserLoginStatusPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="wsGetUserSession">
        <wsdl:part element="tns:wsGetUserSession" name="wsGetUserSession"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="WsGetUserSessionPort">
        <wsdl:operation name="wsGetUserSession">
            <wsdl:input message="tns:wsGetUserSession" name="wsGetUserSession"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QodGetUserSessionBinding" type="tns:WsGetUserSessionPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsGetUserSession">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsGetUserSession">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WsGetUserSessionPortService">
        <wsdl:port binding="tns:QodGetUserSessionBinding" name="GetUserSessionPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="wsResetUsageForAccount">
        <wsdl:part element="tns:wsResetUsageForAccount" name="wsResetUsageForAccount"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="WsResetUsageForAccountPort">
        <wsdl:operation name="wsResetUsageForAccount">
            <wsdl:input message="tns:wsResetUsageForAccount" name="wsResetUsageForAccount"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QodResetUsageForAccountBinding" type="tns:WsResetUsageForAccountPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsResetUsageForAccount">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsResetUsageForAccount">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WsResetUsageForAccountPortService">
        <wsdl:port binding="tns:QodResetUsageForAccountBinding" name="ResetUsageForAccountPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="wsRemoveAccount">
        <wsdl:part element="tns:wsRemoveAccount" name="wsRemoveAccount"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="WsRemoveAccountPort">
        <wsdl:operation name="wsRemoveAccount">
            <wsdl:input message="tns:wsRemoveAccount" name="wsRemoveAccount"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QodRemoveAccountBinding" type="tns:WsRemoveAccountPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsRemoveAccount">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsRemoveAccount">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WsRemoveAccountPortService">
        <wsdl:port binding="tns:QodRemoveAccountBinding" name="RemoveAccountPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>

    <wsdl:message name="wsAddAccount">
        <wsdl:part element="tns:wsAddAccount" name="wsAddAccount"/>
    </wsdl:message>
    <wsdl:portType name="WsAddAccountPort">
        <wsdl:operation name="wsAddAccount">
            <wsdl:input message="tns:wsAddAccount" name="wsAddAccount"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QodAddAccountBinding" type="tns:WsAddAccountPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsAddAccount">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsAddAccount">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WsAddAccountPortService">
        <wsdl:port binding="tns:QodAddAccountBinding" name="AddAccountPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>

    <wsdl:message name="wsUpdateAccount">
        <wsdl:part element="tns:wsUpdateAccount" name="wsUpdateAccount"/>
    </wsdl:message>
    <wsdl:portType name="WsUpdateAccountPort">
        <wsdl:operation name="wsUpdateAccount">
            <wsdl:input message="tns:wsUpdateAccount" name="wsUpdateAccount"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QodUpdateAccountBinding" type="tns:WsUpdateAccountPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsUpdateAccount">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsUpdateAccount">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WsUpdateAccountPortService">
        <wsdl:port binding="tns:QodUpdateAccountBinding" name="UpdateAccountPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="wsGetUserUsageSummary">
        <wsdl:part element="tns:wsGetUserUsageSummary" name="wsGetUserUsageSummary"/>
    </wsdl:message>

    <wsdl:portType name="wsGetUserUsageSummaryPort">
        <wsdl:operation name="wsGetUserUsageSummary">
            <wsdl:input message="tns:wsGetUserUsageSummary" name="wsGetUserUsageSummary"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="QodGetUserUsageSummaryBinding" type="tns:wsGetUserUsageSummaryPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsGetUserUsageSummary">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsGetUserUsageSummary">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="wsGetUserUsageSummaryPortService">
        <wsdl:port binding="tns:QodGetUserUsageSummaryBinding" name="GetUserUsageSummaryPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="wsUpdateUserUsage">
        <wsdl:part element="tns:wsUpdateUserUsage" name="wsUpdateUserUsage"/>
    </wsdl:message>

    <wsdl:portType name="wsUpdateUserUsagePort">
        <wsdl:operation name="wsUpdateUserUsage">
            <wsdl:input message="tns:wsUpdateUserUsage" name="wsUpdateUserUsage"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="QodUpdateUserUsageBinding" type="tns:wsUpdateUserUsagePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsUpdateUserUsage">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsUpdateUserUsage">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="wsUpdateUserUsagePortService">
        <wsdl:port binding="tns:QodUpdateUserUsageBinding" name="UpdateUserUsagePort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="wsLogoffUserSession">
        <wsdl:part element="tns:wsLogoffUserSession" name="wsLogoffUserSession"/>
    </wsdl:message>

    <wsdl:portType name="wsLogoffUserSessionPort">
        <wsdl:operation name="wsLogoffUserSession">
            <wsdl:input message="tns:wsLogoffUserSession" name="wsLogoffUserSession"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="QodLogoffUserSessionBinding" type="tns:wsLogoffUserSessionPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsLogoffUserSession">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsLogoffUserSession">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="wsLogoffUserSessionPortService">
        <wsdl:port binding="tns:QodLogoffUserSessionBinding" name="LogoffUserSessionPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="wsAddServiceToAccount">
        <wsdl:part element="tns:wsAddServiceToAccount" name="wsAddServiceToAccount"/>
    </wsdl:message>

    <wsdl:portType name="wsAddServiceToAccountPort">
        <wsdl:operation name="wsAddServiceToAccount">
            <wsdl:input message="tns:wsAddServiceToAccount" name="wsAddServiceToAccount"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="QodAddServiceToAccountBinding" type="tns:wsAddServiceToAccountPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsAddServiceToAccount">
            <soap:operation soapAction=""/>
            <wsdl:input name="wsAddServiceToAccount">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="wsAddServiceToAccountPortService">
        <wsdl:port binding="tns:QodAddServiceToAccountBinding" name="AddServiceToAccountPort">
            <soap:address location="http://localhost:41080/new-api/QodServices"/>
        </wsdl:port>
    </wsdl:service>


    <!--    <wsdl:message name="wsChangeAddOnSubscription">-->
    <!--        <wsdl:part element="sch:wsChangeAddOnSubscription" name="wsChangeAddOnSubscription"/>-->
    <!--    </wsdl:message>-->

    <!--    <wsdl:portType name="wsChangeAddOnSubscriptionPort">-->
    <!--        <wsdl:operation name="wsChangeAddOnSubscription">-->
    <!--            <wsdl:input message="sch:wsChangeAddOnSubscription" name="wsChangeAddOnSubscription"/>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:portType>-->

    <!--    <wsdl:binding name="QodChangeAddOnSubscriptionBinding" type="sch:wsChangeAddOnSubscriptionPort">-->
    <!--        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>-->
    <!--        <wsdl:operation name="wsChangeAddOnSubscription">-->
    <!--            <soap:operation soapAction=""/>-->
    <!--            <wsdl:input name="wsChangeAddOnSubscription">-->
    <!--                <soap:body use="literal"/>-->
    <!--            </wsdl:input>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:binding>-->

    <!--    <wsdl:service name="wsChangeAddOnSubscriptionPortService">-->
    <!--        <wsdl:port binding="sch:QodChangeAddOnSubscriptionBinding" name="ChangeAddOnSubscriptionPort">-->
    <!--            <soap:address location="http://localhost:41080/new-api/QodServices"/>-->
    <!--        </wsdl:port>-->
    <!--    </wsdl:service>-->


    <!--    <wsdl:message name="wsGetBalance">-->
    <!--        <wsdl:part element="sch:wsGetBalance" name="wsGetBalance"/>-->
    <!--    </wsdl:message>-->

    <!--    <wsdl:portType name="wsGetBalancePort">-->
    <!--        <wsdl:operation name="wsGetBalance">-->
    <!--            <wsdl:input message="sch:wsGetBalance" name="wsGetBalance"/>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:portType>-->

    <!--    <wsdl:binding name="QodGetBalanceBinding" type="sch:wsGetBalancePort">-->
    <!--        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>-->
    <!--        <wsdl:operation name="wsGetBalance">-->
    <!--            <soap:operation soapAction=""/>-->
    <!--            <wsdl:input name="wsGetBalance">-->
    <!--                <soap:body use="literal"/>-->
    <!--            </wsdl:input>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:binding>-->

    <!--    <wsdl:service name="wsGetBalancePortService">-->
    <!--        <wsdl:port binding="sch:QodGetBalanceBinding" name="GetBalancePort">-->
    <!--            <soap:address location="http://localhost:41080/new-api/QodServices"/>-->
    <!--        </wsdl:port>-->
    <!--    </wsdl:service>-->


    <!--    <wsdl:message name="wsSubscribeAddOn">-->
    <!--        <wsdl:part element="sch:wsSubscribeAddOn" name="wsSubscribeAddOn"/>-->
    <!--    </wsdl:message>-->

    <!--    <wsdl:portType name="wsSubscribeAddOnPort">-->
    <!--        <wsdl:operation name="wsSubscribeAddOn">-->
    <!--            <wsdl:input message="sch:wsSubscribeAddOn" name="wsSubscribeAddOn"/>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:portType>-->

    <!--    <wsdl:binding name="QodSubscribeAddOnBinding" type="sch:wsSubscribeAddOnPort">-->
    <!--        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>-->
    <!--        <wsdl:operation name="wsSubscribeAddOn">-->
    <!--            <soap:operation soapAction=""/>-->
    <!--            <wsdl:input name="wsSubscribeAddOn">-->
    <!--                <soap:body use="literal"/>-->
    <!--            </wsdl:input>-->
    <!--        </wsdl:operation>-->
    <!--    </wsdl:binding>-->

    <!--    <wsdl:service name="wsSubscribeAddOnPortService">-->
    <!--        <wsdl:port binding="sch:QodSubscribeAddOnBinding" name="SubscribeAddOnPort">-->
    <!--            <soap:address location="http://localhost:41080/new-api/QodServices"/>-->
    <!--        </wsdl:port>-->
    <!--    </wsdl:service>-->

    <wsdl:service name="SubscriptionService">
        <wsdl:port binding="tns:SubscriptionServiceSoapBinding" name="SubscriptionWS">
            <soap12:address location="http://localhost:41080/new-api/QodServices/"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
