<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://npm.redback.com"
                  xmlns:tnss="http://api.act.com/"
                  xmlns:sch="http://sessionmanagement.ws.nvsmx.elitecore.com/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  targetNamespace="http://npm.redback.com">

    <!-- Define Types (Schemas) -->
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   targetNamespace="http://npm.redback.com"
                   xmlns="http://npm.redback.com"
                   elementFormDefault="qualified">

            <xs:element name="addSubscriberAccountXML">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="addServiceToSubAcctName">
                <xs:complexType>
                    <xs:sequence>
                        <!-- First String Element -->
                        <xs:element name="String_1" form="unqualified">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <!-- Define xsi:type attribute here -->
                                        <xs:attribute name="type" type="xs:string" use="required"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>

                        <!-- Second String Element -->
                        <xs:element name="String_2" form="unqualified">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <!-- Define xsi:type as an attribute in the content -->
                                        <xs:attribute name="type" type="xs:string" use="required"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>

                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="subSessionIsLoggedOn">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getSubAcctName">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getSubscriberAccountXML">
                <xs:complexType>
                    <xs:sequence>
                        <!-- Updated element with xsi:type -->
                        <xs:element name="String_1" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="authenticateSubscriber">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string" minOccurs="0" form="unqualified"/>
                        <xs:element name="String_2" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="removeSubscriberAccount">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getSubscriberSession">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="resetMeteredUsageForSubAcctName">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string" minOccurs="0" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="logonSubSession">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" form="unqualified" type="xs:string"/>
                        <xs:element name="String_2" form="unqualified" type="xs:string"/>
                        <xs:element name="String_3" form="unqualified" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="logoffSubSessions">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="updateSubscriberAccountXML">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="changeAndApplyServicesToSubAcctNameXML">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string" form="unqualified"/>
                        <xs:element name="String_2" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getMeteredVolumeUsageForSubAcctName">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="removeService">
                <xs:complexType>
                    <xs:sequence>
                        <!-- First String Element -->
                        <xs:element name="String_1" form="unqualified" type="xs:string"/>

                        <!-- Second String Element -->
                        <xs:element name="String_2" form="unqualified" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>


            <xs:element name="subAcctNameIsLoggedOn">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="logoffSubSession">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="String_1" type="xs:string" form="unqualified"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>

    <wsdl:types>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://api.act.com/">
        <xs:element name="wsGetBalance">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="actionItem" type="xs:string" minOccurs="0" form="unqualified"/>
                    <xs:element name="requestId" type="xs:string" minOccurs="0" form="unqualified"/>
                    <xs:element name="subscriberId" type="xs:string" minOccurs="0" form="unqualified"/>
                    <xs:element name="alternateId" type="xs:string" minOccurs="0" form="unqualified"/>
                    <xs:element name="packageId" type="xs:long" minOccurs="0" form="unqualified"/>
                    <xs:element name="packageName" type="xs:string" minOccurs="0" form="unqualified"/>
                    <xs:element name="subscriptionId" type="xs:long" minOccurs="0" form="unqualified"/>
                    <xs:element name="parameter1" type="xs:string" minOccurs="0" form="unqualified"/>
                    <xs:element name="parameter2" type="xs:string" minOccurs="0" form="unqualified"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:schema>
    </wsdl:types>


    <wsdl:message name="addSubscriberAccountXMLRequest">
        <wsdl:part element="tns:addSubscriberAccountXML" name="addSubscriberAccountXML"/>
    </wsdl:message>
    <wsdl:portType name="addSubscriberAccountXMLPort">
        <wsdl:operation name="addSubscriberAccountXML">
            <wsdl:input message="tns:addSubscriberAccountXMLRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldaddSubscriberAccountXMLBinding" type="tns:addSubscriberAccountXMLPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="addSubscriberAccountXML">
            <soap:operation soapAction="http://npm.redback.com/addSubscriberAccountXML"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="addSubscriberAccountXMLService">
        <wsdl:port binding="tns:OldaddSubscriberAccountXMLBinding" name="AddSubscriberAccountXMLPort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="addServiceToSubAcctNameRequest">
        <wsdl:part element="tns:addServiceToSubAcctName" name="addServiceToSubAcctName"/>
    </wsdl:message>
    <wsdl:portType name="addServiceToSubAcctNamePort">
        <wsdl:operation name="addServiceToSubAcctName">
            <wsdl:input message="tns:addServiceToSubAcctNameRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldaddServiceToSubAcctNameBinding" type="tns:addServiceToSubAcctNamePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="addServiceToSubAcctName">
            <soap:operation soapAction="http://npm.redback.com/addServiceToSubAcctName"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="addServiceToSubAcctNameService">
        <wsdl:port binding="tns:OldaddServiceToSubAcctNameBinding" name="addServiceToSubAcctNamePort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="subSessionIsLoggedOnRequest">
        <wsdl:part element="tns:subSessionIsLoggedOn" name="subSessionIsLoggedOn"/>
    </wsdl:message>
    <wsdl:portType name="subSessionIsLoggedOnPort">
        <wsdl:operation name="subSessionIsLoggedOn">
            <wsdl:input message="tns:subSessionIsLoggedOnRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldsubSessionIsLoggedOnBinding" type="tns:subSessionIsLoggedOnPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="subSessionIsLoggedOn">
            <soap:operation soapAction="http://npm.redback.com/subSessionIsLoggedOn"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="subSessionIsLoggedOnService">
        <wsdl:port binding="tns:OldsubSessionIsLoggedOnBinding" name="subSessionIsLoggedOnPort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="getSubAcctNameRequest">
        <wsdl:part element="tns:getSubAcctName" name="getSubAcctName"/>
    </wsdl:message>
    <wsdl:portType name="getSubAcctNamePort">
        <wsdl:operation name="getSubAcctName">
            <wsdl:input message="tns:getSubAcctNameRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldgetSubAcctNameBinding" type="tns:getSubAcctNamePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getSubAcctName">
            <soap:operation soapAction="http://npm.redback.com/getSubAcctName"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="getSubAcctNameService">
        <wsdl:port binding="tns:OldgetSubAcctNameBinding" name="getSubAcctNamePort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="getSubscriberAccountXMLRequest">
        <wsdl:part element="tns:getSubscriberAccountXML" name="getSubscriberAccountXML"/>
    </wsdl:message>
    <wsdl:portType name="getSubscriberAccountXMLPort">
        <wsdl:operation name="getSubscriberAccountXML">
            <wsdl:input message="tns:getSubscriberAccountXMLRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldgetSubscriberAccountXMLBinding" type="tns:getSubscriberAccountXMLPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getSubscriberAccountXML">
            <soap:operation soapAction="http://npm.redback.com/getSubscriberAccountXML"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="getSubscriberAccountXMLService">
        <wsdl:port binding="tns:OldgetSubscriberAccountXMLBinding" name="getSubscriberAccountXMLPort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="authenticateSubscriberRequest">
        <wsdl:part element="tns:authenticateSubscriber" name="authenticateSubscriber"/>
    </wsdl:message>
    <wsdl:portType name="authenticateSubscriberPort">
        <wsdl:operation name="authenticateSubscriber">
            <wsdl:input message="tns:authenticateSubscriberRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldauthenticateSubscriberBinding" type="tns:authenticateSubscriberPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="authenticateSubscriber">
            <soap:operation soapAction="http://npm.redback.com/authenticateSubscriber"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="authenticateSubscriberService">
        <wsdl:port binding="tns:OldauthenticateSubscriberBinding" name="authenticateSubscriberPort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="removeSubscriberAccountRequest">
        <wsdl:part element="tns:removeSubscriberAccount" name="removeSubscriberAccount"/>
    </wsdl:message>
    <wsdl:portType name="removeSubscriberAccountPort">
        <wsdl:operation name="removeSubscriberAccount">
            <wsdl:input message="tns:removeSubscriberAccountRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldremoveSubscriberAccountBinding" type="tns:removeSubscriberAccountPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="removeSubscriberAccount">
            <soap:operation soapAction="http://npm.redback.com/removeSubscriberAccount"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="removeSubscriberAccountService">
        <wsdl:port binding="tns:OldremoveSubscriberAccountBinding" name="removeSubscriberAccountPort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="getSubscriberSessionRequest">
        <wsdl:part element="tns:getSubscriberSession" name="getSubscriberSession"/>
    </wsdl:message>
    <wsdl:portType name="getSubscriberSessionPort">
        <wsdl:operation name="getSubscriberSession">
            <wsdl:input message="tns:getSubscriberSessionRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldgetSubscriberSessionBinding" type="tns:getSubscriberSessionPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getSubscriberSession">
            <soap:operation soapAction="http://npm.redback.com/getSubscriberSession"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="getSubscriberSessionService">
        <wsdl:port binding="tns:OldgetSubscriberSessionBinding" name="getSubscriberSessionPort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="resetMeteredUsageForSubAcctNameRequest">
        <wsdl:part element="tns:resetMeteredUsageForSubAcctName" name="resetMeteredUsageForSubAcctName"/>
    </wsdl:message>
    <wsdl:portType name="resetMeteredUsageForSubAcctNamePort">
        <wsdl:operation name="resetMeteredUsageForSubAcctName">
            <wsdl:input message="tns:resetMeteredUsageForSubAcctNameRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldresetMeteredUsageForSubAcctNameBinding" type="tns:resetMeteredUsageForSubAcctNamePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="resetMeteredUsageForSubAcctName">
            <soap:operation soapAction="http://npm.redback.com/resetMeteredUsageForSubAcctName"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="resetMeteredUsageForSubAcctNameService">
        <wsdl:port binding="tns:OldresetMeteredUsageForSubAcctNameBinding" name="resetMeteredUsageForSubAcctNamePort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="logonSubSessionRequest">
        <wsdl:part element="tns:logonSubSession" name="logonSubSession"/>
    </wsdl:message>
    <wsdl:portType name="logonSubSessionPort">
        <wsdl:operation name="logonSubSession">
            <wsdl:input message="tns:logonSubSessionRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldlogonSubSessionBinding" type="tns:logonSubSessionPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="logonSubSession">
            <soap:operation soapAction="http://npm.redback.com/logonSubSession"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="logonSubSessionService">
        <wsdl:port binding="tns:OldlogonSubSessionBinding" name="logonSubSessionPort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="logoffSubSessionsRequest">
        <wsdl:part element="tns:logoffSubSessions" name="logoffSubSessions"/>
    </wsdl:message>
    <wsdl:portType name="logoffSubSessionsPort">
        <wsdl:operation name="logoffSubSessions">
            <wsdl:input message="tns:logoffSubSessionsRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldlogoffSubSessionsBinding" type="tns:logoffSubSessionsPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="logoffSubSessions">
            <soap:operation soapAction="http://npm.redback.com/logoffSubSessions"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="logoffSubSessionsService">
        <wsdl:port binding="tns:OldlogoffSubSessionsBinding" name="logoffSubSessionsPort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="updateSubscriberAccountXMLRequest">
        <wsdl:part element="tns:updateSubscriberAccountXML" name="updateSubscriberAccountXML"/>
    </wsdl:message>
    <wsdl:portType name="updateSubscriberAccountXMLPort">
        <wsdl:operation name="updateSubscriberAccountXML">
            <wsdl:input message="tns:updateSubscriberAccountXMLRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldupdateSubscriberAccountXMLBinding" type="tns:updateSubscriberAccountXMLPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="updateSubscriberAccountXML">
            <soap:operation soapAction="http://npm.redback.com/updateSubscriberAccountXML"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="updateSubscriberAccountXMLService">
        <wsdl:port binding="tns:OldupdateSubscriberAccountXMLBinding" name="updateSubscriberAccountXMLPort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="changeAndApplyServicesToSubAcctNameXMLRequest">
        <wsdl:part element="tns:changeAndApplyServicesToSubAcctNameXML" name="changeAndApplyServicesToSubAcctNameXML"/>
    </wsdl:message>
    <wsdl:portType name="changeAndApplyServicesToSubAcctNameXMLPort">
        <wsdl:operation name="changeAndApplyServicesToSubAcctNameXML">
            <wsdl:input message="tns:changeAndApplyServicesToSubAcctNameXMLRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldchangeAndApplyServicesToSubAcctNameXMLBinding"
                  type="tns:changeAndApplyServicesToSubAcctNameXMLPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="changeAndApplyServicesToSubAcctNameXML">
            <soap:operation soapAction="http://npm.redback.com/changeAndApplyServicesToSubAcctNameXML"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="changeAndApplyServicesToSubAcctNameXMLService">
        <wsdl:port binding="tns:OldchangeAndApplyServicesToSubAcctNameXMLBinding"
                   name="changeAndApplyServicesToSubAcctNameXMLPort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="getMeteredVolumeUsageForSubAcctNameRequest">
        <wsdl:part element="tns:getMeteredVolumeUsageForSubAcctName" name="getMeteredVolumeUsageForSubAcctName"/>
    </wsdl:message>
    <wsdl:portType name="getMeteredVolumeUsageForSubAcctNamePort">
        <wsdl:operation name="getMeteredVolumeUsageForSubAcctName">
            <wsdl:input message="tns:getMeteredVolumeUsageForSubAcctNameRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldgetMeteredVolumeUsageForSubAcctNameBinding" type="tns:getMeteredVolumeUsageForSubAcctNamePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getMeteredVolumeUsageForSubAcctName">
            <soap:operation soapAction="http://npm.redback.com/getMeteredVolumeUsageForSubAcctName"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="getMeteredVolumeUsageForSubAcctNameService">
        <wsdl:port binding="tns:OldgetMeteredVolumeUsageForSubAcctNameBinding"
                   name="getMeteredVolumeUsageForSubAcctNamePort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="removeServiceRequest">
        <wsdl:part element="tns:removeService" name="removeService"/>
    </wsdl:message>
    <wsdl:portType name="removeServicePort">
        <wsdl:operation name="removeService">
            <wsdl:input message="tns:removeServiceRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldremoveServiceBinding" type="tns:removeServicePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="removeService">
            <soap:operation soapAction="http://npm.redback.com/removeService"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="removeServiceService">
        <wsdl:port binding="tns:OldremoveServiceBinding" name="removeServicePort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="subAcctNameIsLoggedOnRequest">
        <wsdl:part element="tns:subAcctNameIsLoggedOn" name="subAcctNameIsLoggedOn"/>
    </wsdl:message>
    <wsdl:portType name="subAcctNameIsLoggedOnPort">
        <wsdl:operation name="subAcctNameIsLoggedOn">
            <wsdl:input message="tns:subAcctNameIsLoggedOnRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldsubAcctNameIsLoggedOnBinding" type="tns:subAcctNameIsLoggedOnPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="subAcctNameIsLoggedOn">
            <soap:operation soapAction="http://npm.redback.com/subAcctNameIsLoggedOn"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="subAcctNameIsLoggedOnService">
        <wsdl:port binding="tns:OldsubAcctNameIsLoggedOnBinding" name="subAcctNameIsLoggedOnPort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


    <wsdl:message name="logoffSubSessionRequest">
        <wsdl:part element="tns:logoffSubSession" name="logoffSubSession"/>
    </wsdl:message>
    <wsdl:portType name="logoffSubSessionPort">
        <wsdl:operation name="logoffSubSession">
            <wsdl:input message="tns:logoffSubSessionRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="OldlogoffSubSessionBinding" type="tns:logoffSubSessionPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="logoffSubSession">
            <soap:operation soapAction="http://npm.redback.com/logoffSubSession"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://npm.redback.com"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <!-- Define Services -->
    <wsdl:service name="logoffSubSessionService">
        <wsdl:port binding="tns:OldlogoffSubSessionBinding" name="logoffSubSessionPort">
            <soap:address location="http://localhost:41080/NPM_API_11.1.1.5/services/ServiceIfcPort"/>
        </wsdl:port>
    </wsdl:service>


        <wsdl:message name="wsGetBalance">
            <wsdl:part element="tnss:wsGetBalance" name="wsGetBalance"> </wsdl:part>
        </wsdl:message>
        <wsdl:portType name="WsGetBalancePort">
            <wsdl:operation name="wsGetBalance">
                <wsdl:input message="tnss:wsGetBalance" name="wsGetBalance"> </wsdl:input>
            </wsdl:operation>
        </wsdl:portType>
        <wsdl:binding name="OldWsGetBalanceBinding" type="tnss:WsGetBalancePort">
            <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
            <wsdl:operation name="wsGetBalance">
                <soap:operation soapAction=""/>
                <wsdl:input name="wsGetBalance">
                    <soap:body use="literal"/>
                </wsdl:input>
            </wsdl:operation>
        </wsdl:binding>
        <wsdl:service name="WsGetBalancePortService">
            <wsdl:port binding="tnss:OldWsGetBalanceBinding" name="GetBalancePort">
                <soap:address location="http://localhost:41080/new-api/QodServices"/>
            </wsdl:port>
        </wsdl:service>


</wsdl:definitions>
