<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://subscriptionWS.ws.nvsmx.elitecore.com/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:ns2="http://schemas.xmlsoap.org/soap/http"
                  xmlns:ns1="http://subscription.ws.nvsmx.elitecore.com/"
                  xmlns:ses="http://sessionmanagement.ws.nvsmx.elitecore.com/"
                  name="SubscriptionService"
                  targetNamespace="http://subscriptionWS.ws.nvsmx.elitecore.com/">

<wsdl:import
            location="http://localhost:41080/new-api/QodServices/finalVasWsdl.wsdl"
            namespace="http://subscription.ws.nvsmx.elitecore.com/"></wsdl:import>

    <wsdl:binding name="SubscriptionServiceSoapBinding" type="ns1:SubscriptionWS">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="wsChangeTopUpSubscription">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsChangeTopUpSubscription">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsChangeTopUpSubscriptionResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsSubscribeTopUp">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsSubscribeTopUp">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsSubscribeTopUpResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>


        <wsdl:operation name="wsSubscribeAddOn">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsSubscribeAddOn">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsSubscribeAddOnResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsChangeAddOnSubscription">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsChangeAddOnSubscription">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsChangeAddOnSubscriptionResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsGetBalance">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsGetBalance">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsGetBalanceResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="wsReauthSessionsBySubscriberIdentity">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="wsReauthSessionsBySubscriberIdentity">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="wsReauthSessionsBySubscriberIdentityResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

    </wsdl:binding>


    <wsdl:service name="SubscriptionService">
        <wsdl:port binding="tns:SubscriptionServiceSoapBinding" name="SubscriptionWS">
            <soap12:address location="http://localhost:41080/new-api/QodServices/"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>