<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://api.act.com/"
           xmlns:tns="http://api.act.com/">

<!-- Define the addAccountResponse complexType -->
        <xs:complexType name="addAccountResponse">
            <xs:sequence>
                <xs:element minOccurs="0" name="requestId" type="xs:string"/>
                <xs:element name="responeCode" type="xs:int"/>
                <xs:element minOccurs="0" name="responseMessage" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>

    <xs:element name="wsAddAccountResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="AddAccount" type="tns:addAccountResponse"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>