server:
  port: 30085

spring:
  application:
    name: SavbillCPMBss-Service
  jackson:
    serialization.write_dates_as_timestamps: false


eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/


#
#ribbon:
#  ReadTimeout: 60000
#  connection-timeout: 3000
#  eureka:
#    enabled: true

#zuul:
#  routes:
#    SavbillRadius-Service:
#      path: /SavbillRadius/**
#      service-id: SavbillRadiusBss-Service
#      strip-prefix: false
#
#    SavbillNotification-Service:
#      path: /SavbillNotification/**
#      service-id: SavbillNotification-Service
#      strip-prefix: false
#
#    SavbillSalesCrmsBss-Service:
#      path: /api/v1/SavbillSalesCrmsBss/**
#      service-id: SavbillSalesCrmsBss-Service
#      strip-prefix: false
#      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#
#    SavbillTaskMgmt-Service:
#      path: /SavbillTaskMgmt/**
#      service-id: SavbillTaskMgmt-Service
#      strip-prefix: false
#
#    SavbillIntegrationSystem-Service:
#      path: /SavbillIntegrationSystem/**
#      service-id: SavbillIntegrationSystem-Service
#      strip-prefix: false
#      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#
#    SavbillKpimanagement-Service:
#      path: /api/v1/KpiManagement/**
#      service-id: SavbillKpimanagement-Service
#      strip-prefix: false
#      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#
#    SavbillSample-Service:
#      path: /api/v1/SavbillSample/**
#      service-id: SavbillSample-Service
#      strip-prefix: false
#      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#
#    SavbillTicketManagement-Service:
#        path: /api/v1/TicketManagement/**
#        service-id: SavbillTicketManagement-Service
#        strip-prefix: false
#        sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#
#    SavbillInventoryManagement-Service:
#      path: /api/v1/SavbillInventoryManagement/**
#      service-id: SavbillInventoryManagement-Service
#      strip-prefix: false
#      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#
#
#    SavbillApiGateWayCommon-Service:
#      path: /api/v1/SavbillApiGateWayCommon/**
#      service-id: SavbillApiGateWayCommon-Service
#      strip-prefix: false
#      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials, Access-Control-Allow-Origin

